SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `{{prefix}}ebay_categories` (
  `CategoryID` int(10) NOT NULL DEFAULT '0',
  `CategoryLevel` int(5) NOT NULL DEFAULT '0',
  `CategoryName` varchar(120) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `CategoryParentID` int(10) NOT NULL DEFAULT '0',
  `LeafCategory` int(1) NOT NULL DEFAULT '0',
  `AutoPayEnabled` int(1) NOT NULL DEFAULT '0',
  `Expired` int(1) NOT NULL DEFAULT '0',
  `IntlAutosFixedCat` int(1) NOT NULL DEFAULT '0',
  `Virtual` int(1) NOT NULL DEFAULT '0',
  `LSD` int(1) NOT NULL DEFAULT '0',
  `ORPA` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CategoryID`),
  KEY `catlevel` (`CategoryLevel`),
  KEY `parent` (`CategoryParentID`),
  KEY `ape` (`AutoPayEnabled`),
  KEY `expired` (`Expired`),
  KEY `IAFC` (`IntlAutosFixedCat`),
  KEY `virtual` (`Virtual`),
  KEY `lsd` (`LSD`),
  KEY `orpa` (`ORPA`),
  KEY `leaf` (`LeafCategory`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `{{prefix}}ebay_products` (
  `Title` varchar(250) NOT NULL DEFAULT '',
  `Category` int(10) NOT NULL DEFAULT '0',
  `Condition` int(1) NOT NULL DEFAULT '0',
  `Image1` varchar(50) DEFAULT NULL,
  `Image2` varchar(50) DEFAULT NULL,
  `Image3` varchar(50) DEFAULT NULL,
  `Image4` varchar(50) DEFAULT NULL,
  `Description` varchar(250) NOT NULL DEFAULT '',
  `Startprice` decimal(10,2) NOT NULL DEFAULT '0.00',
  `Lasting` int(10) NOT NULL DEFAULT '0',
  `EnableBIN` int(1) DEFAULT NULL,
  `BINprice` decimal(10,2) DEFAULT NULL,
  `Qty` int(250) NOT NULL DEFAULT '0',
  `Country` varchar(250) NOT NULL DEFAULT '',
  `Location` varchar(250) NOT NULL DEFAULT '',
  `Paymentmethod` varchar(250) NOT NULL DEFAULT '',
  `Paypalemail` varchar(250) NOT NULL DEFAULT '',
  `Postaldestination` varchar(100) NOT NULL DEFAULT '',
  `Service` varchar(100) NOT NULL DEFAULT '',
  `Postalcost` decimal(10,2) NOT NULL DEFAULT '0.00'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `{{prefix}}ebay_settings` (
  `id` int(11) NOT NULL DEFAULT '1',
  `Currency` varchar(5) DEFAULT NULL,
  `UserToken` varchar(100) DEFAULT NULL,
  `DevID` varchar(50) DEFAULT NULL,
  `AppID` varchar(50) DEFAULT NULL,
  `CertID` varchar(50) DEFAULT NULL,
  `SiteID` int(10) DEFAULT '0',
  `Testmode` int(1) DEFAULT '0',
  `Paypalemail` varchar(200) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `{{prefix}}Searches` (
  `iSearchPK` int(11) NOT NULL AUTO_INCREMENT,
  `vSearchTerm` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iNumberOfSearches` int(11) NOT NULL DEFAULT '0',
  `iRecFoud` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iSearchPK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbAdmin_Security` (
  `iAdminSecid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iUserid_FK` int(11) NOT NULL DEFAULT '0',
  `vSecurity` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iAdminSecid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

INSERT INTO `{{prefix}}tbAdmin_Security` (`iAdminSecid_PK`, `iUserid_FK`, `vSecurity`) VALUES
(1, 1, '1,2,3,4,5,7,8,9,11,12,13,14,15,16,17,18,19,20');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbAdmin_users` (
  `iAdminid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vUsername` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vPassword` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vEmail` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iSuperAdmin` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iAdminid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

INSERT INTO `{{prefix}}tbAdmin_users` (`iAdminid_PK`, `vUsername`, `vPassword`, `vEmail`, `tmBuildDate`, `tmEditDate`, `iSuperAdmin`) VALUES
(1, '{{adminuser}}', PASSWORD('{{adminpass}}'), '{{adminemail}}', '{{timestamp}}', '{{timestamp}}', 1);

CREATE TABLE IF NOT EXISTS `{{prefix}}tbAttributes` (
  `iAttributesid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vAttributeTitle` varchar(60) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iFieldnumber` int(60) NOT NULL DEFAULT '0',
  `vFieldname` text COLLATE utf8_unicode_ci,
  `vPrefix` text COLLATE utf8_unicode_ci,
  `vSuffix` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`iAttributesid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbAttributesValue` (
  `iValueId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iAttributesid_FK` int(11) NOT NULL DEFAULT '0',
  `tValues` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`iValueId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbCompanySettings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vCname` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAddress` text COLLATE utf8_unicode_ci NOT NULL,
  `vCity` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vState` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vStateName` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCountry` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vPhone` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vFax` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vZip` varchar(15) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vFreePhone` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vVatNumber` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vRNumber` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSlogan` text COLLATE utf8_unicode_ci NOT NULL,
  `vLogo` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

INSERT INTO `{{prefix}}tbCompanySettings` (`id`, `vCname`, `vAddress`, `vCity`, `vState`, `vStateName`, `vCountry`, `vPhone`, `vFax`, `vZip`, `vFreePhone`, `vVatNumber`, `vRNumber`, `vSlogan`, `vLogo`) VALUES
(1, 'Company Name', 'Company Address', '', '', '', '', '', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbConfirmation_Orders` (
  `iConfirmation_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iInvoice` smallint(6) DEFAULT NULL,
  `tmLastSendDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iVendorid_FK` int(11) DEFAULT NULL,
  `status` varchar(20) COLLATE utf8_unicode_ci DEFAULT 'pending',
  PRIMARY KEY (`iConfirmation_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbCountry` (
  `iCountryId_PK` bigint(20) NOT NULL AUTO_INCREMENT,
  `vCountryName` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vShortName` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iSortFlag` tinyint(4) NOT NULL DEFAULT '1',
  `fTax` float(10,2) NOT NULL DEFAULT '0.00',
  `vCountryCode` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSageTaxCode` char(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'T9',
  `fShipCharge` decimal(10,2) NOT NULL DEFAULT '0.00',
  `iso3` text COLLATE utf8_unicode_ci NOT NULL,
  `iStatus` int(11) NOT NULL,
  PRIMARY KEY (`iCountryId_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=297 ;

INSERT INTO `{{prefix}}tbCountry` (`iCountryId_PK`, `vCountryName`, `vShortName`, `iSortFlag`, `fTax`, `vCountryCode`, `vSageTaxCode`, `fShipCharge`, `iso3`, `iStatus`) VALUES
(1, 'Afghanistan', 'AF', 1, 0.00, '4', 'T9', 0.00, 'AFG', 1),
(2, 'Antarctica', 'AQ', 1, 0.00, '10', 'T9', 0.00, '', 1),
(22, 'Albania', 'AL', 1, 0.00, '8', 'T9', 0.00, 'ALB', 1),
(23, 'Algeria', 'DZ', 1, 0.00, '12', 'T9', 0.00, 'DZA', 1),
(24, 'American Samoa', 'AS', 1, 0.00, '16', 'T9', 0.00, 'ASM', 1),
(25, 'Andorra', 'AD', 1, 0.00, '20', 'T9', 0.00, 'AND', 1),
(26, 'Angola', 'AO', 1, 0.00, '24', 'T9', 0.00, 'AGO', 1),
(27, 'Anguilla', 'AI', 1, 0.00, '660', 'T9', 0.00, 'AIA', 1),
(29, 'Antigua And Barbuda', 'AG', 1, 0.00, '28', 'T9', 0.00, 'ATG', 1),
(30, 'Argentina', 'AR', 1, 0.00, '32', 'T9', 0.00, 'ARG', 1),
(280, 'Armenia', 'AM', 1, 0.00, '51', 'T9', 0.00, 'ARM', 1),
(31, 'Australia', 'AU', 1, 0.00, '36', 'T9', 0.00, 'AUS', 1),
(32, 'Aruba', 'AW', 1, 0.00, '533', 'T9', 0.00, 'ABW', 1),
(33, 'Austria', 'AT', 1, 0.00, '40', 'T9', 0.00, 'AUT', 1),
(34, 'Azerbaijan', 'AZ', 1, 0.00, '31', 'T9', 0.00, 'AZE', 1),
(35, 'Bahamas', 'BS', 1, 0.00, '44', 'T9', 0.00, 'BHS', 1),
(36, 'Bahrain', 'BH', 1, 0.00, '48', 'T9', 0.00, 'BHR', 1),
(38, 'Bangladesh', 'BD', 1, 0.00, '50', 'T9', 0.00, 'BGD', 1),
(39, 'Barbados', 'BB', 1, 0.00, '52', 'T9', 0.00, 'BRB', 1),
(40, 'Belarus', 'BY', 1, 0.00, '112', 'T9', 0.00, 'BLR', 1),
(41, 'Belgium', 'BE', 1, 0.00, '56', 'T9', 0.00, 'BEL', 1),
(42, 'Belize', 'BZ', 1, 0.00, '84', 'T9', 0.00, 'BLZ', 1),
(43, 'Benin', 'BJ', 1, 0.00, '204', 'T9', 0.00, 'BEN', 1),
(44, 'Bermuda', 'BM', 1, 0.00, '60', 'T9', 0.00, 'BMU', 1),
(45, 'Bhutan', 'BT', 1, 0.00, '64', 'T9', 0.00, 'BTN', 1),
(46, 'Bolivia', 'BO', 1, 0.00, '68', 'T9', 0.00, 'BOL', 1),
(47, 'Botswana', 'BW', 1, 0.00, '72', 'T9', 0.00, 'BWA', 1),
(48, 'Bouvet Island', 'BV', 1, 0.00, '74', 'T9', 0.00, '', 1),
(49, 'Brazil', 'BR', 1, 0.00, '76', 'T9', 0.00, 'BRA', 1),
(50, 'Brunei Darussalam', 'BN', 1, 0.00, '096', 'T9', 0.00, 'BRN', 1),
(51, 'Bulgaria', 'BG', 1, 0.00, '100', 'T9', 0.00, 'BGR', 1),
(52, 'Burkina Faso', 'BF', 1, 0.00, '854', 'T9', 0.00, 'BFA', 1),
(53, 'Burundi', 'BI', 1, 0.00, '108', 'T9', 0.00, 'BDI', 1),
(54, 'Cambodia', 'KH', 1, 0.00, '116', 'T9', 0.00, 'KHM', 1),
(55, 'Cameroon', 'CM', 1, 0.00, '120', 'T9', 0.00, 'CMR', 1),
(57, 'Cape Verde', 'CV', 1, 0.00, '132', 'T9', 0.00, 'CPV', 1),
(58, 'Cayman Islands', 'KY', 1, 0.00, '136', 'T9', 0.00, 'CYM', 1),
(59, 'Chad', 'TD', 1, 0.00, '148', 'T9', 0.00, 'TCD', 1),
(60, 'Chile', 'CL', 1, 0.00, '152', 'T9', 0.00, 'CHL', 1),
(61, 'China', 'CN', 1, 0.00, '156', 'T9', 0.00, 'CHN', 1),
(62, 'Christmas Island', 'CX', 1, 0.00, '162', 'T9', 0.00, '', 1),
(63, 'Cocos Islands', 'CC', 1, 0.00, '166', 'T9', 0.00, '', 1),
(64, 'Colombia', 'CO', 1, 0.00, '170', 'T9', 0.00, 'COL', 1),
(65, 'Comoros', 'KM', 1, 0.00, '174', 'T9', 0.00, 'COM', 1),
(66, 'Congo', 'CG', 1, 0.00, '178', 'T9', 0.00, 'COG', 1),
(67, 'Cook Islands', 'CK', 1, 0.00, '184', 'T9', 0.00, 'COK', 1),
(68, 'Costa Rica', 'CR', 1, 0.00, '188', 'T9', 0.00, 'CRI', 1),
(88, 'Croatia', 'HR', 1, 5.00, '191', 'T9', 0.00, 'HRV', 1),
(89, 'Cuba', 'CU', 1, 0.00, '192', 'T9', 0.00, 'CUB', 1),
(90, 'Cyprus', 'CY', 1, 0.00, '196', 'T9', 0.00, 'CYP', 1),
(91, 'Czech Republic', 'CZ', 1, 0.00, '203', 'T9', 0.00, 'CZE', 1),
(92, 'Denmark', 'DK', 1, 0.00, '208', 'T9', 0.00, 'DNK', 1),
(93, 'Djibouti', 'DJ', 1, 0.00, '262', 'T9', 0.00, 'DJI', 1),
(94, 'Dominica', 'DM', 1, 0.00, '212', 'T9', 0.00, 'DMA', 1),
(95, 'Dominican Republic', 'DO', 1, 0.00, '214', 'T9', 0.00, 'DOM', 1),
(97, 'Ecuador', 'EC', 1, 0.00, '218', 'T9', 0.00, 'ECU', 1),
(98, 'Egypt', 'EG', 1, 0.00, '818', 'T9', 0.00, 'EGY', 1),
(99, 'El Salvador', 'SV', 1, 0.00, '222', 'T9', 0.00, 'SLV', 1),
(100, 'United Kingdom', 'GB', -1, 15.00, '826', 'T9', 9.00, 'GBR', 1),
(101, 'Equatorial Guinea', 'GQ', 1, 0.00, '226', 'T9', 0.00, 'GNQ', 1),
(102, 'Eritrea', 'ER', 1, 0.00, '232', 'T9', 0.00, 'ERI', 1),
(103, 'Estonia', 'EE', 1, 0.00, '233', 'T9', 0.00, 'EST', 1),
(104, 'Ethiopia', 'ET', 1, 0.00, '231', 'T9', 0.00, 'ETH', 1),
(105, 'Falkland Islands', 'FK', 1, 0.00, '238', 'T9', 0.00, 'FLK', 1),
(106, 'Faroe Islands', 'FO', 1, 0.00, '234', 'T9', 0.00, 'FRO', 1),
(107, 'Fiji', 'FJ', 1, 0.00, '242', 'T9', 0.00, 'FJI', 1),
(108, 'Finland', 'FI', 1, 0.00, '246', 'T9', 0.00, 'FIN', 1),
(109, 'France', 'FR', 1, 0.00, '250', 'T9', 0.00, 'FRA', 1),
(110, 'French Guiana', 'GF', 1, 0.00, '254', 'T9', 0.00, 'GUF', 1),
(111, 'French Polynesia', 'PF', 1, 0.00, '258', 'T9', 0.00, 'PYF', 1),
(112, 'Gabon', 'GA', 1, 0.00, '266', 'T9', 0.00, 'GAB', 1),
(113, 'Gambia', 'GM', 1, 0.00, '270', 'T9', 0.00, 'GMB', 1),
(114, 'Georgia', 'GE', 1, 0.00, '268', 'T9', 0.00, 'GEO', 1),
(115, 'Germany', 'DE', 1, 0.00, '276', 'T9', 0.00, 'DEU', 1),
(116, 'Ghana', 'GH', 1, 0.00, '288', 'T9', 0.00, 'GHA', 1),
(117, 'Gibraltar', 'GI', 1, 0.00, '292', 'T9', 0.00, 'GIB', 1),
(118, 'Greece', 'GR', 1, 0.00, '300', 'T9', 0.00, 'GRC', 1),
(119, 'Greenland', 'GL', 1, 0.00, '304', 'T9', 0.00, 'GRL', 1),
(120, 'Grenada', 'GD', 1, 0.00, '308', 'T9', 0.00, 'GRD', 1),
(121, 'Guadeloupe', 'GP', 1, 0.00, '312', 'T9', 0.00, 'GLP', 1),
(122, 'Guam', 'GU', 1, 0.00, '316', 'T9', 0.00, 'GUM', 1),
(123, 'Guatemala', 'GT', 1, 0.00, '320', 'T9', 0.00, 'GTM', 1),
(124, 'Guinea', 'GN', 1, 0.00, '324', 'T9', 0.00, 'GIN', 1),
(125, 'Guinea-bissau', 'GW', 1, 0.00, '624', 'T9', 0.00, 'GNB', 1),
(126, 'Guyana', 'GY', 1, 0.00, '328', 'T9', 0.00, 'GUY', 1),
(127, 'Haiti', 'HT', 1, 0.00, '332', 'T9', 0.00, 'HTI', 1),
(128, 'Honduras', 'HN', 1, 0.00, '340', 'T9', 0.00, 'HND', 1),
(129, 'Hong Kong', 'HK', 1, 0.00, '344', 'T9', 0.00, 'HKG', 1),
(130, 'Hungary', 'HU', 1, 0.00, '348', 'T9', 0.00, 'HUN', 1),
(131, 'Iceland', 'IS', 1, 0.00, '352', 'T9', 0.00, 'ISL', 1),
(132, 'India', 'IN', 1, 0.00, '356', 'T9', 0.00, 'IND', 1),
(133, 'Indonesia', 'ID', 1, 0.00, '360', 'T9', 0.00, 'IDN', 1),
(134, 'Iran', 'IR', 1, 0.00, '364', 'T9', 0.00, 'IRN', 1),
(135, 'Iraq', 'IQ', 1, 0.00, '368', 'T9', 0.00, 'IRQ', 1),
(136, 'Ireland', 'IE', 1, 0.00, '372', 'T9', 0.00, 'IRL', 1),
(137, 'Israel', 'IL', 1, 0.00, '376', 'T9', 0.00, 'ISR', 1),
(138, 'Italy', 'IT', 1, 0.00, '380', 'T9', 0.00, 'ITA', 1),
(139, 'Jamaica', 'JM', 1, 0.00, '388', 'T9', 0.00, 'JAM', 1),
(140, 'Japan', 'JP', 1, 0.00, '392', 'T9', 0.00, 'JPN', 1),
(141, 'Jordan', 'JO', 1, 0.00, '400', 'T9', 0.00, 'JOR', 1),
(142, 'Kazakhstan', 'KZ', 1, 0.00, '398', 'T9', 0.00, 'KAZ', 1),
(143, 'Kenya', 'KE', 1, 0.00, '404', 'T9', 0.00, 'KEN', 1),
(144, 'Kiribati', 'KI', 1, 0.00, '296', 'T9', 0.00, 'KIR', 1),
(145, 'Norfolk Island', 'NF', 1, 0.00, '574', 'T9', 0.00, 'NFK', 1),
(146, 'Korea(North)', 'KP', 1, 0.00, '408', 'T9', 0.00, 'PRK', 1),
(147, 'Kuwait', 'KW', 1, 0.00, '414', 'T9', 0.00, 'KWT', 1),
(148, 'Kyrgyzstan', 'KG', 1, 0.00, '417', 'T9', 0.00, 'KGZ', 1),
(296, 'Laos', 'LA', 1, 0.00, '418', 'T9', 0.00, 'LAO', 1),
(149, 'Latvia', 'LV', 1, 0.00, '428', 'T9', 0.00, 'LVA', 1),
(150, 'Lebanon', 'LB', 1, 0.00, '422', 'T9', 0.00, 'LBN', 1),
(151, 'Lesotho', 'LS', 1, 0.00, '426', 'T9', 0.00, 'LSO', 1),
(152, 'Liberia', 'LR', 1, 0.00, '430', 'T9', 0.00, 'LBR', 1),
(153, 'Libya', 'LY', 1, 0.00, '434', 'T9', 0.00, 'LBY', 1),
(154, 'Liechtenstein', 'LI', 1, 0.00, '438', 'T9', 0.00, 'LIE', 1),
(155, 'Lithuania', 'LT', 1, 0.00, '440', 'T9', 0.00, 'LTU', 1),
(156, 'Luxembourg', 'LU', 1, 0.00, '442', 'T9', 0.00, 'LUX', 1),
(157, 'Macao', 'MO', 1, 0.00, '446', 'T9', 0.00, 'MAC', 1),
(158, 'Macedonia', 'MK', 1, 0.00, '807', 'T9', 0.00, 'MKD', 1),
(159, 'Madagascar', 'MG', 1, 0.00, '450', 'T9', 0.00, 'MDG', 1),
(160, 'Malawi', 'MW', 1, 0.00, '454', 'T9', 0.00, 'MWI', 1),
(161, 'Malaysia', 'MY', 1, 0.00, '458', 'T9', 0.00, 'MYS', 1),
(162, 'Maldives', 'MV', 1, 0.00, '462', 'T9', 0.00, 'MDV', 1),
(163, 'Mali', 'ML', 1, 0.00, '466', 'T9', 0.00, 'MLI', 1),
(164, 'Malta', 'MT', 1, 0.00, '470', 'T9', 0.00, 'MLT', 1),
(165, 'Marshall Islands', 'MH', 1, 0.00, '584', 'T9', 0.00, 'MHL', 1),
(166, 'Martinique', 'MQ', 1, 0.00, '474', 'T9', 0.00, 'MTQ', 1),
(167, 'Mauritania', 'MR', 1, 0.00, '478', 'T9', 0.00, 'MRT', 1),
(168, 'Mauritius', 'MU', 1, 0.00, '480', 'T9', 0.00, 'MUS', 1),
(169, 'Mayotte', 'YT', 1, 0.00, '175', 'T9', 0.00, '', 1),
(170, 'Mexico', 'MX', 1, 0.00, '484', 'T9', 0.00, 'MEX', 1),
(171, 'Micronesia', 'FM', 1, 0.00, '583', 'T9', 0.00, 'FSM', 1),
(172, 'Moldova', 'MD', 1, 0.00, '498', 'T9', 0.00, 'MDA', 1),
(173, 'Monaco', 'MC', 1, 0.00, '492', 'T9', 0.00, 'MCO', 1),
(174, 'Mongolia', 'MN', 1, 0.00, '496', 'T9', 0.00, 'MNG', 1),
(175, 'Montserrat', 'MS', 1, 0.00, '500', 'T9', 0.00, 'MSR', 1),
(176, 'Morocco', 'MA', 1, 0.00, '504', 'T9', 0.00, 'MAR', 1),
(177, 'Mozambique', 'MZ', 1, 0.00, '508', 'T9', 0.00, 'MOZ', 1),
(178, 'Myanmar', 'MM', 1, 0.00, '104', 'T9', 0.00, 'MMR', 1),
(179, 'Namibia', 'NA', 1, 0.00, '516', 'T9', 0.00, 'NAM', 1),
(180, 'Nauru', 'NR', 1, 0.00, '520', 'T9', 0.00, 'NRU', 1),
(181, 'Nepal', 'NP', 1, 0.00, '524', 'T9', 0.00, 'NPL', 1),
(182, 'Netherlands', 'NL', 1, 0.00, '528', 'T9', 0.00, 'NLD', 1),
(183, 'Netherlands Antilles', 'AN', 1, 0.00, '530', 'T9', 0.00, 'ANT', 1),
(184, 'New Caledonia', 'NC', 1, 0.00, '540', 'T9', 0.00, 'NCL', 1),
(185, 'New Zealand', 'NZ', 1, 0.00, '554', 'T9', 0.00, 'NZL', 1),
(186, 'Nicaragua', 'NI', 1, 0.00, '558', 'T9', 0.00, 'NIC', 1),
(188, 'Nigeria', 'NG', 1, 0.00, '566', 'T9', 0.00, 'NGA', 1),
(191, 'Norway', 'NO', 1, 0.00, '578', 'T9', 0.00, 'NOR', 1),
(192, 'Oman', 'OM', 1, 0.00, '512', 'T9', 0.00, 'OMN', 1),
(193, 'Pakistan', 'PK', 1, 0.00, '586', 'T9', 0.00, 'PAK', 1),
(194, 'Palau', 'PW', 1, 0.00, '585', 'T9', 0.00, 'PLW', 1),
(195, 'Panama', 'PA', 1, 0.00, '591', 'T9', 0.00, 'PAN', 1),
(196, 'Papua New Guinea', 'PG', 1, 0.00, '598', 'T9', 0.00, 'PNG', 1),
(197, 'Paraguay', 'PY', 1, 0.00, '600', 'T9', 0.00, 'PRY', 1),
(198, 'Peru', 'PE', 1, 0.00, '604', 'T9', 0.00, 'PER', 1),
(199, 'Philippines', 'PH', 1, 0.00, '608', 'T9', 0.00, 'PHL', 1),
(201, 'Poland', 'PL', 1, 0.00, '616', 'T9', 0.00, 'POL', 1),
(202, 'Portugal', 'PT', 1, 0.00, '620', 'T9', 0.00, 'PRT', 1),
(204, 'Qatar', 'QA', 1, 0.00, '634', 'T9', 0.00, 'QAT', 1),
(206, 'Romania', 'RO', 1, 0.00, '642', 'T9', 0.00, 'ROM', 1),
(207, 'Russian Federation', 'RU', 1, 0.00, '', 'T9', 0.00, '', 1),
(208, 'Rwanda', 'RW', 1, 0.00, '646', 'T9', 0.00, 'RWA', 1),
(209, 'Saint Lucia', 'LC', 1, 0.00, '662', 'T9', 0.00, 'LCA', 1),
(210, 'Samoa', 'WS', 1, 0.00, '882', 'T9', 0.00, 'WSM', 1),
(211, 'San Marino', 'SM', 1, 0.00, '674', 'T9', 0.00, 'SMR', 1),
(212, 'Saudi Arabia', 'SA', 1, 0.00, '682', 'T9', 0.00, 'SAU', 1),
(214, 'Senegal', 'SN', 1, 0.00, '686', 'T9', 0.00, 'SEN', 1),
(215, 'Seychelles', 'SC', 1, 0.00, '690', 'T9', 0.00, 'SYC', 1),
(216, 'Sierra Leone', 'SL', 1, 0.00, '694', 'T9', 0.00, 'SLE', 1),
(217, 'Singapore', 'SG', 1, 0.00, '702', 'T9', 0.00, 'SGP', 1),
(218, 'Slovakia', 'SK', 1, 0.00, '703', 'T9', 0.00, 'SVK', 1),
(219, 'Slovenia', 'SI', 1, 0.00, '705', 'T9', 0.00, 'SVN', 1),
(220, 'Solomon Islands', 'SB', 1, 0.00, '90', 'T9', 0.00, 'SLB', 1),
(221, 'Somalia', 'SO', 1, 0.00, '706', 'T9', 0.00, 'SOM', 1),
(222, 'South Africa', 'ZA', 1, 0.00, '710', 'T9', 0.00, 'ZAF', 1),
(225, 'Spain', 'ES', 1, 0.00, '724', 'T9', 0.00, 'ESP', 1),
(226, 'Sri Lanka', 'LK', 1, 0.00, '144', 'T9', 0.00, 'LKA', 1),
(228, 'Sudan', 'SD', 1, 0.00, '736', 'T9', 0.00, 'SDN', 1),
(229, 'Suriname', 'SR', 1, 0.00, '740', 'T9', 0.00, 'SUR', 1),
(230, 'Swaziland', 'SZ', 1, 0.00, '748', 'T9', 0.00, 'SWZ', 1),
(231, 'Sweden', 'SE', 1, 0.00, '752', 'T9', 0.00, 'SWE', 1),
(232, 'Switzerland', 'CH', 1, 0.00, '756', 'T9', 0.00, 'CHE', 1),
(233, 'Syrian Arab Republic', 'SY', 1, 0.00, '', 'T9', 0.00, '', 1),
(234, 'Taiwan', 'TW', 1, 0.00, '158', 'T9', 0.00, 'TWN', 1),
(235, 'Tajikistan', 'TJ', 1, 0.00, '762', 'T9', 0.00, 'TJK', 1),
(236, 'Tanzania', 'TZ', 1, 0.00, '834', 'T9', 0.00, 'TZA', 1),
(237, 'Thailand', 'TH', 1, 0.00, '764', 'T9', 0.00, 'THA', 1),
(241, 'Tonga', 'TO', 1, 0.00, '776', 'T9', 0.00, 'TON', 1),
(243, 'Tunisia', 'TN', 1, 0.00, '788', 'T9', 0.00, 'TUN', 1),
(244, 'Turkey', 'TR', 1, 0.00, '792', 'T9', 0.00, 'TUR', 1),
(245, 'Turkmenistan', 'TM', 1, 0.00, '795', 'T9', 0.00, 'TKM', 1),
(247, 'Tuvalu', 'TV', 1, 0.00, '798', 'T9', 0.00, 'TUV', 1),
(248, 'Uganda', 'UG', 1, 0.00, '800', 'T9', 0.00, 'UGA', 1),
(249, 'Ukraine', 'UA', 1, 0.00, '804', 'T9', 0.00, 'UKR', 1),
(250, 'United Arab Emirates', 'AE', 1, 0.00, '784', 'T9', 0.00, 'ARE', 1),
(251, 'United States', 'US', 0, 6.00, '840', 'T9', 3.00, 'USA', 1),
(252, 'Uruguay', 'UY', 1, 0.00, '858', 'T9', 0.00, 'URY', 1),
(253, 'Uzbekistan', 'UZ', 1, 0.00, '860', 'T9', 0.00, 'UZB', 1),
(254, 'Vanuatu', 'VU', 1, 0.00, '548', 'T9', 0.00, 'VUT', 1),
(255, 'Vatican City', 'VA', 1, 0.00, '336', 'T9', 0.00, 'VAT', 1),
(256, 'Venezuela', 'VE', 1, 0.00, '862', 'T9', 0.00, 'VEN', 1),
(257, 'Vietnam', 'VN', 1, 0.00, '704', 'T9', 0.00, 'VNM', 1),
(258, 'Virgin Islands, British', 'VI', 1, 0.00, '850', 'T9', 0.00, 'VIR', 1),
(260, 'Yemen', 'YE', 1, 0.00, '887', 'T9', 0.00, 'YEM', 1),
(263, 'Zambia', 'ZM', 1, 0.00, '894', 'T9', 0.00, 'ZMB', 1),
(264, 'Zimbabwe', 'ZW', 1, 0.00, '716', 'T9', 0.00, 'ZWE', 1),
(265, 'British Indian Ocean Territory', 'IO', 1, 0.00, '86', 'T9', 0.00, '', 1),
(266, 'Bosnia and Herzegovina', 'BA', 1, 0.00, '70', 'T9', 0.00, 'BIH', 1),
(267, 'Central African Republic', 'CF', 1, 0.00, '140', 'T9', 0.00, 'CAF', 1),
(268, 'Congo, Democratic Republic of the', 'CD', 1, 0.00, '180', 'T9', 0.00, 'COD', 1),
(269, 'Cote d''Ivoire', 'CI', 1, 0.00, '', 'T9', 0.00, '', 1),
(270, 'Heard Island and McDonald Islands', 'HM', 1, 0.00, '334', 'T9', 0.00, '', 1),
(271, 'Niger', 'NE', 1, 0.00, '562', 'T9', 0.00, 'NER', 1),
(272, 'Palestinian Territory', 'PS', 1, 0.00, '275', 'T9', 0.00, '', 1),
(273, 'Pitcairn', 'PN', 1, 0.00, '612', 'T9', 0.00, 'PCN', 1),
(274, 'Puerto Rico', 'PR', 1, 0.00, '630', 'T9', 0.00, 'PRI', 1),
(275, 'Saint Helena', 'SH', 1, 0.00, '654', 'T9', 0.00, 'SHN', 1),
(276, 'Saint Kitts and Nevis', 'KN', 1, 0.00, '659', 'T9', 0.00, 'KNA', 1),
(277, 'Saint Pierre and Miquelon', 'PM', 1, 0.00, '666', 'T9', 0.00, 'SPM', 1),
(278, 'Saint Vincent and the Grenadines', 'VC', 1, 0.00, '670', 'T9', 0.00, 'VCT', 1),
(279, 'Sao Tome and Principe', 'ST', 1, 0.00, '678', 'T9', 0.00, 'STP', 1),
(292, 'Serbia and Montenegro', 'CS', 1, 0.00, '891', 'T9', 0.00, '', 1),
(281, 'South Georgia', 'GS', 1, 0.00, '239', 'T9', 0.00, '', 1),
(282, 'Korea(South)', 'KR', 1, 0.00, '410', 'T9', 0.00, 'KOR', 1),
(283, 'Svalbard and Jan Mayen', 'SJ', 1, 0.00, '744', 'T9', 0.00, 'SJM', 1),
(284, 'Timor-Leste', 'TL', 1, 0.00, '626', 'T9', 0.00, '', 1),
(285, 'Togo', 'TG', 1, 0.00, '768', 'T9', 0.00, 'TGO', 1),
(286, 'Tokelau', 'TK', 1, 0.00, '772', 'T9', 0.00, 'TKL', 1),
(287, 'Trinidad and Tobago', 'TT', 1, 0.00, '780', 'T9', 0.00, 'TTO', 1),
(288, 'United States Minor Outlying Islands', 'UM', 1, 0.00, '581', 'T9', 0.00, '', 1),
(289, 'Virgin Islands, U.S.', 'VG', 1, 0.00, '092', 'T9', 0.00, 'VGB', 1),
(290, 'Wallis and Futuna', 'WF', 1, 0.00, '876', 'T9', 0.00, 'WLF', 1),
(291, 'Western Sahara', 'EH', 1, 0.00, '732', 'T9', 0.00, 'ESH', 1);

CREATE TABLE IF NOT EXISTS `{{prefix}}tbfusion` (
  `fusionId` int(11) NOT NULL AUTO_INCREMENT,
  `iOwner_FK` int(11) NOT NULL DEFAULT '0',
  `iSubId_FK` int(11) NOT NULL DEFAULT '0',
  `vtype` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iSort` smallint(6) NOT NULL DEFAULT '0',
  `iState` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `vOwnerType` varchar(15) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`fusionId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=49 ;

INSERT INTO `{{prefix}}tbfusion` (`fusionId`, `iOwner_FK`, `iSubId_FK`, `vtype`, `iSort`, `iState`, `vOwnerType`) VALUES
(1, 0, 1, 'department', 1, 1, 'department'),
(2, 0, 2, 'department', 2, 1, 'department'),
(3, 1, 1, 'product', 12, 1, 'department'),
(18, 0, 2, 'product', 10, 1, 'department'),
(48, 2, 2, 'product', 1, 1, 'department'),
(42, 0, 2, 'content', 2, 1, 'department'),
(19, 0, 1, 'product', 11, 1, 'department'),
(36, 1, 2, 'product', 1, 1, 'product');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMailroom` (
  `iMailid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vSubject` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iStatus` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `vSid` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tHtmlMail` text COLLATE utf8_unicode_ci,
  `tTextMail` text COLLATE utf8_unicode_ci,
  `iSentHtml` int(11) DEFAULT '0',
  `iSentText` int(11) DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmSentDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vUserList` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vVisitorList` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iMailid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMailroomLead` (
  `iLeadid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vdescription` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iLeadid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMailroomLeadList` (
  `iLeadListid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iLeadId_FK` int(11) NOT NULL DEFAULT '0',
  `iCustomerid_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`iLeadListid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMailroomLeadProducts` (
  `iLeadProductId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iLeadId_FK` int(11) NOT NULL DEFAULT '0',
  `iProductid_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`iLeadProductId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMenuheaders` (
  `iHeaderid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vHeader` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vImage` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iState` int(3) NOT NULL DEFAULT '0',
  `iSort` int(3) NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iHeaderid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbMenuItems` (
  `iMenuItemsId` int(11) NOT NULL AUTO_INCREMENT,
  `iHeaderid_FK` int(11) DEFAULT NULL,
  `vItemtitle` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vLink` varchar(250) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vHrefAttributes` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vImage` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iState` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iMethod` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iSort` smallint(6) NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iMenuItemsId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbModules` (
  `mId` bigint(20) NOT NULL AUTO_INCREMENT,
  `sName` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vDisplayName` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iActive` tinyint(1) NOT NULL DEFAULT '1',
  `isAuth` tinyint(1) NOT NULL DEFAULT '1',
  `display` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`mId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=21 ;

INSERT INTO `{{prefix}}tbModules` (`mId`, `sName`, `vDisplayName`, `iActive`, `isAuth`, `display`) VALUES
(1, 'security', 'Administrator', 1, 1, 1),
(2, 'ec_show', 'Shop Builder', 1, 1, 1),
(3, 'ec_menu', 'Menu Builder', 1, 1, 1),
(4, 'ec_option', 'Product options', 1, 1, 1),
(5, 'ec_package', 'Product Package', 1, 1, 1),
(6, 'loginCheck', 'login', 1, 0, 0),
(7, 'user', 'Customers', 1, 1, 1),
(8, 'supplier', 'Suppliers', 1, 1, 1),
(9, 'enquiry', 'Enquiries', 1, 1, 1),
(11, 'orders', 'Invoices', 1, 1, 1),
(12, 'settings', 'Shop Settings', 1, 1, 1),
(13, 'email', 'Email Campaigns', 1, 1, 1),
(14, 'promotions', 'Promotions', 1, 1, 1),
(15, 'report', 'Reports', 1, 1, 1),
(16, 'csv', 'Product Importer', 1, 1, 1),
(17, 'plugin', 'Plugins', 1, 1, 1),
(18, 'froogle', 'Froogle feeds', 1, 1, 1),
(20, 'mobicart', 'MobiCart', 1, 1, 1);

CREATE TABLE IF NOT EXISTS `{{prefix}}tbNewsletter` (
  `iSignup_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vEmail` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iSignup_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPlugin_apps` (
  `iPluginid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vAppName` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vTemplate` varchar(75) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDescription` text COLLATE utf8_unicode_ci,
  `vVersion` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tHelp` text COLLATE utf8_unicode_ci,
  `vSecurity` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iState` smallint(6) NOT NULL DEFAULT '0',
  `iMod` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iPluginid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostageCity` (
  `iCityId` int(20) NOT NULL AUTO_INCREMENT,
  `vStateId` text NOT NULL,
  `vCountryId` text NOT NULL,
  PRIMARY KEY (`iCityId`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostageCityDetails` (
  `iRangeId` int(20) NOT NULL AUTO_INCREMENT,
  `fMinweight` float(10,2) NOT NULL,
  `fMaxWeight` float(10,2) NOT NULL,
  `fCost` float(10,2) NOT NULL,
  `fCityId` varchar(20) NOT NULL,
  `fSpecialDelivery` float(10,2) NOT NULL,
  PRIMARY KEY (`iRangeId`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostageMethodDetails` (
  `iPostDescId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iPostId_FK` int(11) NOT NULL DEFAULT '0',
  `vDescription` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vField1` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vField2` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vField3` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iPostDescId_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=6 ;

INSERT INTO `{{prefix}}tbPostageMethodDetails` (`iPostDescId_PK`, `iPostId_FK`, `vDescription`, `vField1`, `vField2`, `vField3`) VALUES
(1, 1, 'NULL', '0', '0', ''),
(2, 2, 'NULL', '0', '0', ''),
(3, 3, 'NULL', '0', '0', ''),
(4, 8, 'NULL', '0', '0', ''),
(5, 5, 'NULL', '0', 'unlimited', '1');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostageMethods` (
  `iPostId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vMethodName` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDescription` text COLLATE utf8_unicode_ci NOT NULL,
  `iStatus` int(11) NOT NULL DEFAULT '0',
  `fBaseRate` float(10,2) NOT NULL DEFAULT '0.00',
  `iDefaultHighest` tinyint(4) NOT NULL DEFAULT '0',
  `vKey` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iPostId_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=11 ;

INSERT INTO `{{prefix}}tbPostageMethods` (`iPostId_PK`, `vMethodName`, `vDescription`, `iStatus`, `fBaseRate`, `iDefaultHighest`, `vKey`) VALUES
(1, 'Flat rate', 'One rate for all orders', 0, 0.00, 0, 'flat'),
(2, 'Percentage', 'Postage based on percentage of total sale', 0, 0.00, 0, 'percent'),
(3, 'Per item', 'Postage charged on a per item basis', 0, 0.00, 0, 'peritem'),
(4, 'Postage codes', 'Set postage codes to use on individual products', 0, 0.00, 0, 'codes'),
(5, 'Postal Range', 'Postage charge based on range of total order', 0, 0.00, 0, 'range'),
(6, 'Special rates', 'Setup special rates which users can select during checkout', 0, 0.00, 0, 'special'),
(7, 'No postage', 'All orders will have Free postage', 1, 0.00, 0, 'free'),
(8, 'Postage by weight', 'Setup postage by weight calculation factor', 0, 0.00, 0, 'pweight'),
(9, 'International Postage', 'Setup Postage cost by zones', 0, 0.00, 0, 'zones'),
(10, 'Postage by State', 'Setup Postage cost by State', 0, 0.00, 0, 'cities');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostagezoneDetails` (
  `iRangeId` int(20) NOT NULL AUTO_INCREMENT,
  `fMinweight` float(10,2) DEFAULT NULL,
  `fMaxWeight` float(10,2) NOT NULL DEFAULT '0.00',
  `fCost` float(10,2) NOT NULL DEFAULT '0.00',
  `iZoneId` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fSpecialDelivery` float(10,2) DEFAULT NULL,
  PRIMARY KEY (`iRangeId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbPostagezones` (
  `iZoneId` int(20) NOT NULL AUTO_INCREMENT,
  `vZonename` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCountryId` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`iZoneId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbProductAttributes` (
  `iAttributeid_FK` int(10) NOT NULL DEFAULT '0',
  `iProductid_FK` int(10) NOT NULL DEFAULT '0',
  `iValueid_FK` int(10) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbsettings` (
  `iSettingid` int(11) NOT NULL AUTO_INCREMENT,
  `vDatatype` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSmalltext` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tLargetext` text COLLATE utf8_unicode_ci,
  `nNumberdata` double DEFAULT NULL,
  `tmDateData` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `sConstantName` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `default_value` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iAdminUser` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iSettingid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=294 ;

INSERT INTO `{{prefix}}tbsettings` (`iSettingid`, `vDatatype`, `vSmalltext`, `tLargetext`, `nNumberdata`, `tmDateData`, `tmEditDate`, `sConstantName`, `default_value`, `iAdminUser`) VALUES
(6, 'invoice', NULL, NULL, 10000, '{{timestamp}}', '{{timestamp}}', 'CONST_INVOICE', '', 1),
(17, 'index_body', 'Home Page', '<div style="position:relative;left:-12px">	<img src="graphics/clean/homepage_large.png" style="width:927px;height:416px;" />	<div style="position:absolute;top:24px;right:-240px;">		<div style="font-size:45px;color:#393F4C;width:473px;line-height:100%;text-align:left;">			{TPL_VAR_SLOGAN}</div>		<div style="font-family:arial;width:456px;margin-top:40px;margin-right:17px;font-size:16px;line-height:110%;">			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>	</div></div><p>	&nbsp;</p>', NULL, '{{timestamp}}', '{{timestamp}}', 'INDEX_BODY', '', 1),
(20, 'member_points', 'Member Points', '<p>Member Points are a great way to get FREE products. The more you purchase, the more you earn. You can apply your points earned on future purchases.</p>			<p>Once you have signed up as a customer and started earning points, you can then redeem your points at anytime on your next purchases.</p>', NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(32, 'dsn', '{{dsn}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(33, 'dbUserName', '{{dbuser}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(34, 'dbPassword', '{{dbpass}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(36, 'SITEURL', '{{siteurl}}/', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SITE_URL', '', 1),
(38, 'SITEPATH', '{{sitepath}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SITE_PATH', '', 1),
(42, 'membership', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'OFFERMPOINT', '', 1),
(43, 'memberPointValue', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'MPOINTVALUE', '', 1),
(44, 'memberPointCalculation', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'MPOINTCALCULATION', '', 1),
(51, 'cartPayPal', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(52, 'cartPayCCp', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(53, 'cartPayEFT', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(54, 'cartPayCOD', '0.00', NULL, 10, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(55, 'cartPayMail', NULL, NULL, 1, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(56, 'cartCCTypeMC', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'MASTERCARD', '', 1),
(57, 'cartCCTypeVisa', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'VISA', '', 1),
(58, 'cartCCTypeAmex', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'AMEX', '', 1),
(116, 'dbType', 'mysql', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(134, 'dbServer', 'localhost', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(139, 'inventory', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'STOCK_CHECK', '', 1),
(137, 'customerReviews', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'CUSTOMER_REVIEWS', '', 1),
(138, 'wishlist', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'USEWISHLIST', '', 1),
(135, 'cartPayCC', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(119, 'cartCCTypeDiscover', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'DISCOVER', '', 1),
(120, 'cartCCTypeSwitch', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'SWITCHCARD', '', 1),
(121, 'cartCCTypeMaestro', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'MAESTRO', '', 1),
(59, 'cartCCTypeSolo', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'SOLO', '', 1),
(60, 'cartCCTypeDiners', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'DINERS_CLUB', '', 1),
(63, 'cartInfoEmail', '{{adminemail}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'ENQUIRY_EMAIL', '', 1),
(67, 'cartDefaultShipping', 'P&amp;P', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'DEFAULT_POSTAGE_NAME', '', 1),
(122, 'accessibility', 'Accessibility statement', '<p>This website has been designed to be accessible to as many people as possible. If you have difficulty using our site please let us know and we will do our best to rectify this in future maintenance and development.</p><ol><li>All pages on this site comply with all priority 1, 2, and 3 guidelines of the <a href="http://www.w3.org/TR/WCAG10/">W3C Web Content Accessibility Guidelines</a>. </li>   <li>All pages on this site <a href="http://validator.w3.org/check/referer">validate as XHTML 1.0 Transitional</a>. </li>	<li>This site is built using structured semantic markup. <code>H2</code> tags are used for main titles to aid users of screen reading software such as <a title="Freedom Scientific - screen reading software" href="http://www.freedomscientific.com/fs_products/software_jaws.asp">JAWS</a>. For example, on this page, JAWS users can skip to the next section within the accessibility statement by pressing <kbd>ALT+INSERT+2</kbd>. </li></ol><h2>Navigation aids</h2><ol>	<li>All pages have been authored to include Link Relationships to aid navigation in text-only browsers such as <a title="A free text-only web browser for blind users with refreshable Braille displays" href="http://lynx.browser.org/">Lynx</a> and graphical browsers that support this feature. </li>    <li>This site has been coded to ensure a logical tab order through links and form elements. Keyboard navigation is possible via the <kbd>TAB KEY</kbd> on your keyboard. Alternatively Opera users can use the <kbd>A KEY</kbd> to navigate links and the <kbd>TAB KEY</kbd> to navigate form elements. </li>    <li>A Skip Navigation link has been provided to allow users of text-only browsers and screen readers to bypass the site navigation to quickly access its content. </li></ol><h2>Visual design</h2> <ol>	<li><a title="learn more about Cascading Style Sheets" href="http://www.w3.org/Style/CSS/">Cascading Style Sheets</a> (CSS) are used to control visual layout throughout this site. </li> <li>This site uses only relative font sizes, compatible with the user-specified ''text size'' option in visual browsers.To display web page ext larger or smaller go to the ''View'' menu in your browser, point to Text Size, and then click the size you want (this may differ depending on browser vendor). </li>	<li>If your browser or browsing device does not support Cascading Style Sheets, the content of this site will still be readable and usable. </li></ol></p>', NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(123, 'conditions', 'Terms &amp; conditions', '<p>UK legal documents available from <a href="http://www.clickdocs.co.uk/internet-law.htm?AffiliateID=143">Click Docs</a>', NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(124, 'privacy', 'Privacy policy', '<p>UK legal documents available from <a href="http://www.clickdocs.co.uk/internet-law.htm?AffiliateID=143">Click Docs</a>', NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(125, 'contact', 'Contact Us', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(126, 'cartCCTypeVisaDelta', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'VISA_DELTA', '', 1),
(127, 'cartCCTypeVisaElectron', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'VISA_ELECTRON', '', 1),
(132, 'ADMINEMAIL', '{{adminemail}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'ADMIN_EMAIL', '', 1),
(133, 'CURRENCY', '&pound;', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'CONST_CURRENCY', '', 1),
(136, 'cartOrderEmail', '{{adminemail}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'ORDER_EMAIL', '', 1),
(140, 'cartWeightPrice', '10', NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(141, 'cartRealTimeProcess', '', NULL, 0, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(142, 'dbPrefix', '{{prefix}}', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(143, 'cartAlternateShipping', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'DELIVERY_ADDRESS', '', 1),
(144, 'cartSecureServer', '{{safeurl}}', NULL, 1, '{{timestamp}}', '{{timestamp}}', 'SITE_SAFEURL', '', 1),
(145, 'cartMailList', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'MAIL_LIST', '', 1),
(146, 'systemstate', '0', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SYSTEM_STATE', '', 1),
(147, 'metatitle', NULL, 'Default Meta Title', NULL, '{{timestamp}}', '{{timestamp}}', 'META_TITLE', '', 1),
(148, 'metadescription', NULL, 'Default Meta Description', NULL, '{{timestamp}}', '{{timestamp}}', 'META_DESCRIPTION', '', 1),
(149, 'metakeyword', NULL, 'Default Meta Keywords', NULL, '{{timestamp}}', '{{timestamp}}', 'META_KEYWORD', '', 1),
(150, 'cartGiftWrapping', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'ENABLE_GIFTWRAP', '', 1),
(151, 'imgUploadJPGCompression', NULL, NULL, 75, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_JPGCOMPRESSION', '', 1),
(152, 'imgUploadSmallWidth', NULL, NULL, 217, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_SMIMAGEWIDTH', '', 1),
(153, 'imgUploadSmallHeight', NULL, NULL, 217, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_SMIMAGEHEIGHT', '', 1),
(154, 'imgUploadMediumWidth', NULL, NULL, 220, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_MDIMAGEWIDTH', '', 1),
(155, 'imgUploadMediumHeight', NULL, NULL, 220, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_MDIMAGEHEIGHT', '', 1),
(156, 'imgUploadLargeWidth', NULL, NULL, 350, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_LGIMAGEWIDTH', '', 1),
(157, 'imgUploadLargeHeight', NULL, NULL, 350, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_LGIMAGEHEIGHT', '', 1),
(158, 'imgUploadDeptSmallWidth', NULL, NULL, 140, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_DEPTSMIMAGEWIDTH', '', 1),
(159, 'imgUploadDeptSmallHeight', NULL, NULL, 70, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_DEPTSMIMAGEHEIGHT', '', 1),
(160, 'imgUploadDeptMediumWidth', NULL, NULL, 220, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_DEPTMDIMAGEWIDTH', '', 1),
(161, 'imgUploadDeptMediumHeight', NULL, NULL, 220, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_DEPTMDIMAGEHEIGHT', '', 1),
(162, 'imgUploadContentSmallWidth', NULL, NULL, 140, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_CONTENTSMIMAGEWIDTH', '', 1),
(163, 'imgUploadContentSmallHeight', NULL, NULL, 140, '{{timestamp}}', '{{timestamp}}', 'UPLOAD_CONTENTSMIMAGEHEIGHT', '', 1),
(164, 'analyticsCode', NULL, 'UA-XXXXX-X', NULL, '{{timestamp}}', '{{timestamp}}', 'ANALYTICSCODE', '', 1),
(165, 'payPalId', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'PAYPAL_ID', '', 1),
(166, 'paymentCurrency', 'GBP', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'PAYMENT_CURRENCY', '', 1),
(167, 'authorizeNetLogin', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'AUTHORIZEPAYMENT_LOGIN', '', 1),
(168, 'authorizeNetType', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'AUTHORIZEPAYMENT_TYPE', '', 1),
(169, 'authorizeNetKey', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'AUTHORIZEPAYMENT_KEY', '', 1),
(170, 'protxVendor', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'PROTX_VENDOR', '', 1),
(173, 'gatewayTestmode', NULL, NULL, 1, '{{timestamp}}', '{{timestamp}}', 'GATEWAY_TESTMODE', '', 1),
(174, 'secpayMerchant', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SECPAY_MERCHANT', '', 1),
(175, 'secpayRemotePassword', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SECPAY_REMOTEPASSWORD', '', 1),
(176, 'secpayDigestKey', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SECPAY_DIGESTKEY', '', 1),
(177, 'cartsecpay', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(178, 'cartWirelessEmail', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'WIRELESS_EMAIL', '', 1),
(179, 'VerisignPartner', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'VERISIGN_PARTNER', '', 1),
(180, 'VerisignLogin', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'VERISIGN_LOGIN', '', 1),
(181, 'VerisignUser', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'VERISIGN_USER', '', 1),
(182, 'VerisignPassword', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'VERISIGN_PASSWORD', '', 1),
(183, 'HSBCKey', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'HSBC_KEY', '', 1),
(184, 'HSBCStorefrontId', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'HSBC_STOREID', '', 1),
(185, 'HSBCCurrency', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'HSBC_CURRENCY', '', 1),
(186, 'WorldpayInstid', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'WORLDPAY_INSTID', '', 1),
(187, 'BarclayClientId', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'BARCLAYS_CLIENTID', '', 1),
(188, 'BarclayPassword', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'BARCLAYS_PASSWORD', '', 1),
(189, 'BarclayOid', NULL, NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'BARCLAYS_OID', '', 1),
(191, 'SpecialPostage', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'SPECIAL_POSTAGE', '', 1),
(192, 'iTreeMenu', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'TREE_MENU', '', 1),
(193, 'SMTP_AUTH', '0', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SMTP_AUTH', '', 1),
(194, 'SMTP_USERNAME', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SMTP_USERNAME', '', 1),
(195, 'SMTP_PASSWORD', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SMTP_PASSWORD', '', 1),
(196, 'SMTP_HOST', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SMTP_HOST', '', 1),
(197, 'protxApplyAvsCv2', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'PROTX_APPLY_AVS_CV2', '', 1),
(198, 'protx3DSecureStatus', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'PROTX_3D_SECURE_STATUS', '', 1),
(199, 'rrptext', 'R.R.P.', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'RRP_TEXT', '', 1),
(200, 'cencoding', '2', NULL, NULL, '{{timestamp}}', '{{timestamp}}', '', '', 1),
(202, 'vTaxName', 'V.A.T.', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'VAT_TAX_TEXT', '', 1),
(203, 'mainLayout', 'layout.htm', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'MAIN_LAYOUT', '', 1),
(204, 'homeLayout', 'homepage.htm', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'HOMEPAGE_LAYOUT', '', 1),
(205, 'seo_friendly', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'SEOFRIENDLY', '', 1),
(206, 'SecureTradingMerchantId', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SECURETRADING_MERCHANTID', '', 1),
(207, 'SecureTradingCurrency', '', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'SECURETRADING_CURRENCY', '', 1),
(208, 'deptlimit', '2', NULL, NULL, '{{timestamp}}', '{{timestamp}}', 'DEPT_PRODUCT_LIMIT', '', 1),
(209, 'vatbaserate', NULL, NULL, 17, '{{timestamp}}', '{{timestamp}}', 'DEFAULTVATTAX', '', 1),
(210, 'incvat', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'INC_VAT', '', 1),
(275, 'IncVatTextFlag', NULL, NULL, 1, '{{timestamp}}', '{{timestamp}}', 'INC_VAT_FLAG', '', 1),
(211, 'postagevatonoff', NULL, NULL, 0, '{{timestamp}}', '{{timestamp}}', 'VAT_POSTAGE_FLAG', '', 1),
(212, 'Language', 'English.php', NULL, 1, '', '', 'LANGUAGE_PACK', '', 1),
(213, 'dropshipFeature', '1', NULL, 1, '', '', 'DROP_SHIP_FEATURE', '', 1),
(214, 'databaseVersion', '6.00', NULL, 1, '', '', 'DATABASE_VERSION', '', 1),
(215, 'minordertotal', NULL, NULL, 0, '', '', 'MINORDERTOTAL', '', 1),
(216, 'shopbybrand', '1', NULL, 1, '', '', 'SHOPBYBRAND', '', 1),
(217, 'newsletternav', '1', NULL, 1, '', '', 'NEWSLETTER_NAV', '', 1),
(218, 'topsellers', '0', NULL, 0, '', '', 'TOPSELLERS', '', 1),
(219, 'usecompare', '1', NULL, 1, '', '', 'USECOMPARE', '', 1),
(220, 'recent', '1', NULL, 1, '', '', 'RECENTVIEWED', '', 1),
(221, 'netgross', NULL, NULL, 0, '', '', 'NETGROSS', '', 1),
(222, 'rssproducts', NULL, NULL, 0, '', '', 'RSSPRODUCT', '', 1),
(223, 'rssarticles', NULL, NULL, 0, '', '', 'RSSARTICLES', '', 1),
(224, 'PayPalApiUser', '', NULL, NULL, '', '', 'PAYPALAPI_USERNAME', '', 1),
(225, 'PayPalApiPass', '', NULL, NULL, '', '', 'PAYPALAPI_PASSWORD', '', 1),
(226, 'PayPalApiSig', '', NULL, NULL, '', '', 'PAYPALAPI_SIGNATURE', '', 1),
(227, 'PayPalApiEnd', '', NULL, NULL, '', '', 'PAYPALAPI_ENDPOINT', '', 1),
(228, 'imgGalleryThumbnailWidth', NULL, NULL, 40, '', '', 'GALLERY_THUMBNAILWIDTH', '', 1),
(229, 'imgGalleryThumbnailHeight', NULL, NULL, 40, '', '', 'GALLERY_THUMBNAILHEIGHT', '', 1),
(230, 'imgGalleryLargeWidth', NULL, NULL, 250, '', '', 'GALLERY_LARGEWIDTH', '', 1),
(231, 'imgGalleryLargeHeight', NULL, NULL, 250, '', '', 'GALLERY_LARGEHEIGHT', '', 1),
(232, 'wholesale', NULL, NULL, 0, '', '', 'ENABLE_WHOLESALE', '', 1),
(233, 'STClientId', NULL, NULL, NULL, '', '', 'SECURETRADING_CLIENTID', '', 1),
(234, 'STPassword', NULL, NULL, NULL, '', '', 'SECURETRADING_PASSWORD', '', 1),
(235, 'STSiteref', NULL, NULL, NULL, '', '', 'STREFERENCE', '', 1),
(236, 'captcha_registration', '0', NULL, NULL, '', '', 'CAPTCHA_REGISTRATION', '', 1),
(237, 'captcha_contactus', '0', NULL, NULL, '', '', 'CAPTCHA_CONTACTUS', '', 1),
(238, 'SageVendorname', NULL, NULL, NULL, '', '', 'SAGE_VENDORNAME', '', 1),
(239, 'SageEncryptionpass', NULL, NULL, NULL, '', '', 'SAGE_ENCRYPTEDPASSWORD', '', 1),
(240, 'Sagetransactiontype', NULL, NULL, NULL, '', '', 'SAGE_TRANSACTIONTYPE', '', 1),
(241, 'Sagecurrency', NULL, NULL, NULL, '', '', 'SAGE_CURRENCY', '', 1),
(242, 'marginpercent', NULL, NULL, 0, '', '', 'MARGINPERCENT', '', 1),
(243, 'marginstatus', 'original', NULL, NULL, '', '', 'MARGINSTATUS', '', 1),
(244, 'propay_accnumber', NULL, NULL, NULL, '', '', 'PROPAY_ACCNUMBER', '', 1),
(245, 'propay_certstring', NULL, NULL, NULL, '', '', 'PROPAY_CERTSTRING', '', 1),
(246, 'propay_canada', NULL, NULL, NULL, '', '', 'PROPAY_CANADA', '', 1),
(251, 'LocalLicense', NULL, '', NULL, '', '', 'LOCALLICENSE', '', 1),
(252, 'LicenseKey', '{{license}}', NULL, NULL, '', '', 'LICENSEKEY', '', 1),
(253, 'hidenovat', NULL, NULL, NULL, '', '', 'HIDENOVAT', '', 1),
(254, 'ThemeRealPath', '{{sitepath}}modules/', NULL, NULL, '', '', 'THEMEPATH', '', 1),
(255, 'AdminThemeRealPath', '{{sitepath}}modules/', NULL, NULL, '', '', 'ADMINTHEMEPATH', '', 1),
(256, 'ThemeUrlPath', '{{safeurl}}', NULL, NULL, '', '', 'THEMEURLPATH', '', 1),
(257, 'AdminThemeUrlPath', '{{safeurl}}', NULL, NULL, '', '', 'ADMINTHEMEURLPATH', '', 1),
(258, 'AdminActiveTheme', 'default', NULL, NULL, '', '', '', '', 1),
(259, 'ActiveTheme', 'default', NULL, NULL, '', '', '', '', 1),
(261, 'SelectedGateway', '0', NULL, NULL, '', '', 'SELECTED_PAYMENTGATEWAY', '', 1),
(262, 'CardSaveID', '0', NULL, NULL, '', '', 'CS_MERCHANT_ID', '', 1),
(263, 'CardSavePass', '0', NULL, NULL, '', '', 'CS_MERCHANT_PASS', '', 1),
(264, 'CardSaveURL', 'paymentprocessor.net', NULL, NULL, '', '', 'CS_GATEWAY_DOMAIN', '', 1),
(265, 'CardSavePORT', '4430', NULL, NULL, '', '', 'CS_GATEWAY_PORT', '', 1),
(266, 'CardSaveKey', '0', NULL, NULL, '', '', 'CS_SECRET_KEY', '', 1),
(267, 'CardRSaveMerchantID', '0', NULL, NULL, '', '', 'CSr_MERCHANT_ID', '', 1),
(268, 'CardRSavePassword', '0', NULL, NULL, '', '', 'CSr_MERCHANT_PASS', '', 1),
(269, 'CardRSaveKey', '0', NULL, NULL, '', '', 'CSr_KEY', '', 1),
(270, 'CardRSaveDomain', 'paymentprocessor.net', NULL, NULL, '', '', 'CSr_DOMAIN', '', 1),
(271, 'CardRSaveResults', '0', NULL, NULL, '', '', 'CSr_RESULTS_DISPLAY', '', 1),
(272, 'CardRSaveCV2', '1', NULL, NULL, '', '', 'CSr_CV2_MANDATORY', '', 1),
(273, 'CardSaveCurrency', '826', NULL, NULL, '', '', 'CS_CURRENCY', '', 1),
(274, 'CardRSaveCurrency', '826', NULL, NULL, '', '', 'CSr_CURRENCY', '', 1),
(280, 'RecentlyViewedLimit', NULL, NULL, 0, '', '', 'RVP_LIMIT', '', 1),
(281, 'PaymentSenseID', '', NULL, NULL, '', '', 'PS_MERCHANT_ID', '', 1),
(282, 'PaymentSensePass', '', NULL, NULL, '', '', 'PS_MERCHANT_PASS', '', 1),
(283, 'PaymentSenseURL', 'paymentsensegateway.com', NULL, NULL, '', '', 'PS_GATEWAY_DOMAIN', '', 1),
(284, 'PaymentSensePORT', '4430', NULL, NULL, '', '', 'PS_GATEWAY_PORT', '', 1),
(285, 'PaymentSenseKey', '', NULL, NULL, '', '', 'PS_SECRET_KEY', '', 1),
(286, 'PaymentSenseCurrency', '826', NULL, NULL, '', '', 'PS_CURRENCY', '', 1),
(287, 'PaymentRSenseMerchantID', '', NULL, NULL, '', '', 'PSr_MERCHANT_ID', '', 1),
(288, 'PaymentRSensePassword', '', NULL, NULL, '', '', 'PSr_MERCHANT_PASS', '', 1),
(289, 'PaymentRSenseKey', '', NULL, NULL, '', '', 'PSr_KEY', '', 1),
(290, 'PaymentRSenseDomain', 'paymentsensegateway.com', NULL, NULL, '', '', 'PSr_DOMAIN', '', 1),
(291, 'PaymentRSenseResults', '0', NULL, NULL, '', '', 'PSr_RESULTS_DISPLAY', '', 1),
(292, 'PaymentRSenseCV2', '1', NULL, NULL, '', '', 'PSr_CV2_MANDATORY', '', 1),
(293, 'PaymentRSenseCurrency', '826', NULL, NULL, '', '', 'PSr_CURRENCY', '', 1);

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_choices` (
  `iChoiceid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vName` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDescription` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iUseInventory` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iInventory` int(11) NOT NULL DEFAULT '0',
  `iBackorder` int(11) NOT NULL DEFAULT '0',
  `vType` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fPrice` double NOT NULL DEFAULT '0',
  `iState` int(11) NOT NULL DEFAULT '0',
  `vImage` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iChoiceid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Compare` (
  `iCompareid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iCustomerid_FK` int(11) DEFAULT NULL,
  `iProductid_FK` int(11) DEFAULT NULL,
  `vQuantity` int(11) NOT NULL DEFAULT '0',
  `iOrderid_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`iCompareid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_content` (
  `iContentid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vTitle` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSeoTitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tShortDescription` text COLLATE utf8_unicode_ci,
  `vMetaTitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tMetaDescription` text COLLATE utf8_unicode_ci,
  `tKeywords` text COLLATE utf8_unicode_ci,
  `tContent` text COLLATE utf8_unicode_ci,
  `vImage1` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage2` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage3` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vTemplate` varchar(60) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vLayout` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iContentid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Creditcards` (
  `iCCid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCCnumber` varchar(50) COLLATE utf8_unicode_ci DEFAULT '0',
  `vCCtype` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCCyear` varchar(5) COLLATE utf8_unicode_ci DEFAULT '0',
  `vCCmonth` varchar(10) COLLATE utf8_unicode_ci DEFAULT '0',
  `vCCstart_year` varchar(5) COLLATE utf8_unicode_ci DEFAULT '0',
  `vCCstart_month` varchar(10) COLLATE utf8_unicode_ci DEFAULT '0',
  `vAba` varchar(50) COLLATE utf8_unicode_ci DEFAULT '0',
  `vAcct` varchar(50) COLLATE utf8_unicode_ci DEFAULT '0',
  `vCCissuenumber` varchar(5) COLLATE utf8_unicode_ci DEFAULT '0',
  PRIMARY KEY (`iCCid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Departments` (
  `iDeptid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vTitle` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSeoTitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tShortDescription` text COLLATE utf8_unicode_ci,
  `vMetaTitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tMetaDescription` text COLLATE utf8_unicode_ci,
  `tKeywords` text COLLATE utf8_unicode_ci,
  `tContent` text COLLATE utf8_unicode_ci,
  `vImage1` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage2` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage3` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vTemplate` varchar(60) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vLayout` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iDisplayInNav` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iMember` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iDeptid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

INSERT INTO `{{prefix}}tbShop_Departments` (`iDeptid_PK`, `vTitle`, `vSeoTitle`, `tShortDescription`, `vMetaTitle`, `tMetaDescription`, `tKeywords`, `tContent`, `vImage1`, `vImage2`, `vImage3`, `vTemplate`, `vLayout`, `iDisplayInNav`, `iMember`, `tmBuildDate`, `tmEditDate`, `vAdminUser`) VALUES
(1, 'Orange T-Shirts', 'orange_t-shirts', '', '', '', '', '', '', '', '', 'department.htm', 'layout.htm', '1', '0', '1332356437', '1336688675', '1'),
(2, 'Blue T-Shirts', 'blue_t-shirts', '', '', '', '', '', '', '', '', 'department.htm', 'layout.htm', '1', '0', '1332356472', '1336325263', '1');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_discounts` (
  `iDiscountid` int(11) NOT NULL AUTO_INCREMENT,
  `vCode` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fDiscount` double NOT NULL DEFAULT '0',
  `fMinimum` double NOT NULL DEFAULT '0',
  `fFixamount` double NOT NULL DEFAULT '0',
  `tmStartDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEndDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iUseonce` smallint(1) unsigned NOT NULL DEFAULT '0',
  `iState` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iDiscountid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_giftcerts` (
  `iGiftcertid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vGiftcode` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `fAmount` float NOT NULL DEFAULT '0',
  `fRemaining` float NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iGiftcertid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_giftwrap` (
  `iGiftwrapid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vTitle` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vImage` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImageLarge` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vDescription` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fPrice` float DEFAULT NULL,
  `iSort` smallint(6) NOT NULL DEFAULT '0',
  `iState` smallint(6) NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iGiftwrapid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Options` (
  `iOptionid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vName` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDescription` varchar(200) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iState` int(12) NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iOptionid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_OptionValues` (
  `iOptionValueid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOptionid_FK` int(11) NOT NULL DEFAULT '0',
  `vOptSku` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vItem` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fPrice` double NOT NULL DEFAULT '0',
  `iInventory` int(11) NOT NULL DEFAULT '0',
  `iUseInventory` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iBackorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `vImage` varchar(50) COLLATE utf8_unicode_ci DEFAULT '0',
  `iSort` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`iOptionValueid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_OrderChoices` (
  `iChoiceid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` int(11) DEFAULT NULL,
  `iProductid_FK` int(11) DEFAULT NULL,
  `iProductOrderid_FK` int(11) DEFAULT NULL,
  `iChoiceid_FK` int(11) DEFAULT NULL,
  `vChoiceValue` varchar(250) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDescription` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fPrice` float DEFAULT '0',
  `vType` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iChoiceid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Orderkits` (
  `iKitOid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` int(11) DEFAULT NULL,
  `iProductOrderid_FK` int(11) DEFAULT NULL,
  `iKitid` int(11) NOT NULL DEFAULT '0',
  `iProductid_FK` int(11) DEFAULT NULL,
  `iKitItem_id` int(11) NOT NULL DEFAULT '0',
  `iKitgroup` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iKitItem_title` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iKitOid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_OrderOptions` (
  `iOptionid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` int(11) DEFAULT NULL,
  `iProductid_FK` int(11) DEFAULT NULL,
  `iProductOrderid_FK` int(11) DEFAULT NULL,
  `iOptionid` int(11) DEFAULT NULL,
  `vName` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vItem` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vOptSku` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fPrice` double DEFAULT NULL,
  PRIMARY KEY (`iOptionid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_OrderProducts` (
  `iOrderProductid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` int(11) DEFAULT NULL,
  `iProductid_FK` int(11) DEFAULT NULL,
  `iVendorid_FK` int(11) DEFAULT NULL,
  `iQty` int(11) NOT NULL DEFAULT '0',
  `iGiftwrapFK` int(11) DEFAULT NULL,
  `fPrice` double(10,2) NOT NULL DEFAULT '0.00',
  `fDiscount` double(10,2) NOT NULL DEFAULT '0.00',
  `vTitle` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `seo_title` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSku` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vSupplierSku` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iKit` tinyint(4) DEFAULT '0',
  `tShortDescription` text COLLATE utf8_unicode_ci,
  `tSupplierDescription` text COLLATE utf8_unicode_ci,
  `vSeoTitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iTaxable` tinyint(3) DEFAULT '0',
  `iFreeship` tinyint(3) DEFAULT '0',
  `vPostageNotes` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iOrderProductid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Orders` (
  `iOrderid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderCount` int(11) NOT NULL DEFAULT '0',
  `iCustomerid_FK` int(11) DEFAULT NULL,
  `iInvoice` int(11) NOT NULL DEFAULT '0',
  `tmOrderDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPayMethod` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vShipDescription` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vShipMethod_Id` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `fShipTotal` double(10,2) NOT NULL DEFAULT '0.00',
  `fShipByWeightKg` float DEFAULT NULL,
  `fShipByWeightPrice` float(10,2) NOT NULL DEFAULT '0.00',
  `vFirstName` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vLastName` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vEmail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAddress1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAddress2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCity` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vState` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vStateName` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCountry` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vZip` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCompany` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPhone` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vHomepage` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iSameAsBilling` tinyint(4) DEFAULT '0',
  `vAltName` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltAddress1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltAddress2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltCity` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltState` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltStateName` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAltCountry` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltZip` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAltPhone` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fCodCharge` double NOT NULL DEFAULT '0',
  `vDiscountCode` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `fDiscount` double NOT NULL DEFAULT '0',
  `vPromotion` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fPromoValue` double(10,2) DEFAULT NULL,
  `vPromoDescription` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iGiftcert_FK` int(11) DEFAULT NULL,
  `fGiftcertTotal` double NOT NULL DEFAULT '0',
  `fTaxRate` double NOT NULL DEFAULT '0',
  `fTaxPrice` double(10,2) DEFAULT NULL,
  `tComments` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'None',
  `vCustomerIP` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tAdminComments` text COLLATE utf8_unicode_ci NOT NULL,
  `vAid` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vSid` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vStatus` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'New',
  `fMemberPoints` double(10,2) NOT NULL DEFAULT '0.00',
  `iPayStatus` smallint(6) NOT NULL DEFAULT '0',
  `fTotalPrice` double DEFAULT NULL,
  `tmDeliveryDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmPostDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iOrderStatus` tinyint(4) NOT NULL DEFAULT '0',
  `iTransactionId` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vSessionId` varchar(35) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vRemote_address` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vProtx_apply_avs_cv2` set('0','1','2','3') COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vProtx_3d_secure_status` set('0','1','2','3') COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vSecurityKey` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `v3DSecureStatus` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iEarnedPoints` float(10,2) NOT NULL DEFAULT '0.00',
  `vInvoiceEdit` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAuthCode` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `vAltCompany` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iOrderid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_OrderShip` (
  `iOrderShipid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iOrderid_FK` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vShipper` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vTracking` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmShipDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iOrderShipid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_ProductChoices` (
  `iChoiceid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iProductid_FK` int(11) DEFAULT NULL,
  `iChoiceid` int(11) DEFAULT NULL,
  `iSort` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iChoiceid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_ProductKits` (
  `iKitId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iKitId` int(11) NOT NULL DEFAULT '0',
  `iProdId_FK` int(11) NOT NULL DEFAULT '0',
  `iQty` smallint(6) NOT NULL DEFAULT '1',
  `iSort` smallint(6) NOT NULL DEFAULT '1',
  PRIMARY KEY (`iKitId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_ProductOptions` (
  `iOptionid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iProductid_FK` int(11) DEFAULT NULL,
  `iOptionid` int(11) DEFAULT NULL,
  `iSort` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`iOptionid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Products` (
  `iProdid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vTitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSeoTitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tShortDescription` text COLLATE utf8_unicode_ci,
  `tSupplierDescription` text COLLATE utf8_unicode_ci,
  `vMetaTitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tMetaDescription` text COLLATE utf8_unicode_ci,
  `tKeywords` text COLLATE utf8_unicode_ci,
  `tContent` text COLLATE utf8_unicode_ci,
  `vImage1` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage2` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vImage3` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tImages` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vDownloadablefile` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vTemplate` varchar(60) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vLayout` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vSku` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vSupplierSku` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fListPrice` decimal(10,2) NOT NULL DEFAULT '0.00',
  `fPrice` decimal(10,2) NOT NULL DEFAULT '0.00',
  `fRetailPrice` decimal(10,2) NOT NULL DEFAULT '0.00',
  `fItemWeight` float NOT NULL DEFAULT '0',
  `iInventory` int(11) NOT NULL DEFAULT '0',
  `iInventoryMinimum` int(11) NOT NULL DEFAULT '0',
  `iBackorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iUseinventory` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iOnorder` int(11) NOT NULL DEFAULT '0',
  `tmDuedate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vShipCode` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vShipNotes` varchar(75) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iFreeShip` tinyint(3) NOT NULL DEFAULT '0',
  `iTaxable` tinyint(3) NOT NULL DEFAULT '0',
  `iIncVat` tinyint(3) DEFAULT NULL,
  `iVendorid_FK` int(11) NOT NULL DEFAULT '0',
  `iAttrValueId_FK` int(250) DEFAULT '0',
  `iDiscount` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iSale` tinyint(3) unsigned DEFAULT NULL,
  `fPointIncrease` float NOT NULL DEFAULT '0',
  `iCartButton` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iEnquiryButton` int(1) NOT NULL DEFAULT '0',
  `iKit` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iViewCount` int(11) NOT NULL DEFAULT '0',
  `iAddCount` int(11) NOT NULL DEFAULT '0',
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iProdid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

INSERT INTO `{{prefix}}tbShop_Products` (`iProdid_PK`, `vTitle`, `vSeoTitle`, `tShortDescription`, `tSupplierDescription`, `vMetaTitle`, `tMetaDescription`, `tKeywords`, `tContent`, `vImage1`, `vImage2`, `vImage3`, `tImages`, `vDownloadablefile`, `vTemplate`, `vLayout`, `vSku`, `vSupplierSku`, `fListPrice`, `fPrice`, `fRetailPrice`, `fItemWeight`, `iInventory`, `iInventoryMinimum`, `iBackorder`, `iUseinventory`, `iOnorder`, `tmDuedate`, `vShipCode`, `vShipNotes`, `tmBuildDate`, `tmEditDate`, `iFreeShip`, `iTaxable`, `iIncVat`, `iVendorid_FK`, `iAttrValueId_FK`, `iDiscount`, `iSale`, `fPointIncrease`, `iCartButton`, `iEnquiryButton`, `iKit`, `iViewCount`, `iAddCount`, `iAdminUser`) VALUES
(1, 'Orange T-Shirt', 'orange_t-shirt', 'A very nice Orange T-Shirt', NULL, '', '', '', '<p>    A very <strong>nice</strong> Orange T-Shirt that is very bright and is very orange. It even has an orange on it. And around it.</p>', 'orange1337106152_58.png', 'orange1337106159_132.png', 'orange.png', 'black_tshirt1336000319_7301336061995_662.jpg,orange1337205986_693.png,orange1337205992_671.png,orange1337205998_842.png,orange1337208195_964.png,orange1337208189_150.png,', '', 'productpackage.htm', 'layout.htm', 'OT1', NULL, 0.00, 10.50, 5.00, 1, 0, 0, 0, 0, 0, '', '0', '', '1332356967', '1337208195', 0, 0, NULL, 0, 0, 0, 0, 0, 1, 0, 1, 1408, 174, '1'),
(2, 'Blue T-Shirt', 'blue_t-shirt', '', NULL, '', '', '', '<p>    A Lovely blue shirt :)&nbsp;</p><ul> <li>        Blue</li> <li>        12&quot;</li> <li>        Yellow</li></ul>', 'blue.png', 'blue1337106108_588.png', 'blue1337106115_810.png', ',,,,,,', '', 'productpackage.htm', 'layout.htm', 'BTS', NULL, 0.00, 10.50, 0.00, 0, 0, 0, 0, 0, 0, '', '0', '', '1335986245', '1337201690', 0, 0, NULL, 0, 0, 0, 1, 0, 1, 0, 0, 140, 92, '1');

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Promotions` (
  `iPromotionid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vPromotype` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fCarttotal` float DEFAULT NULL,
  `fDiscount` float(10,2) DEFAULT NULL,
  `iRangefield` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iSort` tinyint(4) DEFAULT '3',
  `tmStartDate` int(14) DEFAULT NULL,
  `tmEndDate` int(14) DEFAULT NULL,
  `tmEditDate` int(14) DEFAULT NULL,
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`iPromotionid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_vdiscounts` (
  `iDiscountId` int(11) NOT NULL AUTO_INCREMENT,
  `iProductId_FK` int(11) NOT NULL DEFAULT '0',
  `iRangea` smallint(6) NOT NULL DEFAULT '0',
  `iRangeb` smallint(6) NOT NULL DEFAULT '0',
  `fDiscount` float(10,2) NOT NULL DEFAULT '0.00',
  `iSort` smallint(6) NOT NULL DEFAULT '1',
  PRIMARY KEY (`iDiscountId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbShop_Wishlist` (
  `iShopWishid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iCustomerid_FK` int(11) DEFAULT NULL,
  `iProductid_FK` int(11) DEFAULT NULL,
  `vQuantity` int(11) NOT NULL DEFAULT '0',
  `iOrderid_FK` int(11) DEFAULT NULL,
  PRIMARY KEY (`iShopWishid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbState` (
  `iStateId_PK` bigint(20) NOT NULL AUTO_INCREMENT,
  `vStateName` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vShortName` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iCountryID_FK` bigint(20) DEFAULT NULL,
  `fTax` float(10,2) DEFAULT NULL,
  `bBother` enum('Y','N') COLLATE utf8_unicode_ci DEFAULT NULL,
  `iTaxOnFullTotal` tinyint(4) NOT NULL DEFAULT '0',
  `fShipCharge` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`iStateId_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=254 ;

INSERT INTO `{{prefix}}tbState` (`iStateId_PK`, `vStateName`, `vShortName`, `iCountryID_FK`, `fTax`, `bBother`, `iTaxOnFullTotal`, `fShipCharge`) VALUES
(1, 'Alaska', 'AK', 251, 0.00, 'N', 0, 0.00),
(2, 'Arkansas', 'AR', 251, 0.00, 'N', 0, 0.00),
(3, 'Alabama', 'AL', 251, 0.00, 'N', 0, 0.00),
(4, 'Arizona', 'AZ', 251, 0.00, 'N', 0, 0.00),
(5, 'California', 'CA', 251, 0.00, 'N', 0, 0.00),
(6, 'Colorado', 'CO', 251, 0.00, 'N', 0, 0.00),
(7, 'Connecticut', 'CT', 251, 0.00, 'N', 0, 0.00),
(9, 'Delaware', 'DE', 251, 0.00, 'N', 0, 0.00),
(10, 'Florida', 'FL', 251, 0.00, 'N', 0, 0.00),
(12, 'Georgia', 'GA', 251, 0.00, 'N', 0, 0.00),
(14, 'Hawaii', 'HI', 251, 0.00, 'N', 0, 0.00),
(15, 'Iowa', 'IA', 251, 0.00, 'N', 0, 0.00),
(16, 'Idaho', 'ID', 251, 0.00, 'N', 0, 0.00),
(17, 'Illinois', 'IL', 251, 0.00, 'N', 0, 0.00),
(18, 'Indiana', 'IN', 251, 0.00, 'N', 0, 0.00),
(19, 'Kansas', 'KS', 251, 0.00, 'N', 0, 0.00),
(20, 'Kentucky', 'KY', 251, 0.00, 'N', 0, 0.00),
(21, 'Louisiana', 'LA', 251, 0.00, 'N', 0, 0.00),
(22, 'Massachusetts', 'MA', 251, 0.00, 'N', 0, 0.00),
(23, 'Maryland', 'MD', 251, 0.00, 'N', 0, 0.00),
(24, 'Maine', 'ME', 251, 0.00, 'N', 0, 0.00),
(26, 'Michigan', 'MI', 251, 0.00, 'N', 0, 0.00),
(27, 'Minnesota', 'MN', 251, 0.00, NULL, 0, 0.00),
(28, 'Missouri', 'MO', 251, 0.00, NULL, 0, 0.00),
(30, 'Mississippi', 'MS', 251, 0.00, NULL, 0, 0.00),
(31, 'Montana', 'MT', 251, 0.00, NULL, 0, 0.00),
(32, 'North Carolina', 'NC', 251, 0.00, NULL, 0, 0.00),
(33, 'North Dakota', 'ND', 251, 0.00, NULL, 0, 0.00),
(34, 'Nebraska', 'NE', 251, 0.00, NULL, 0, 0.00),
(38, 'Nevada', 'NV', 251, 0.00, NULL, 0, 0.00),
(35, 'New Hampshire', 'NH', 251, 0.00, NULL, 0, 0.00),
(36, 'New Jersey', 'NJ', 251, 0.00, NULL, 0, 0.00),
(37, 'New Mexico', 'NM', 251, 0.00, NULL, 0, 0.00),
(39, 'New York', 'NY', 251, 0.00, NULL, 0, 0.00),
(40, 'Ohio', 'OH', 251, 0.00, NULL, 0, 0.00),
(41, 'Oklahoma', 'OK', 251, 0.00, NULL, 0, 0.00),
(42, 'Oregon', 'OR', 251, 0.00, NULL, 0, 0.00),
(43, 'Pennsylvania', 'PA', 251, 0.00, NULL, 0, 0.00),
(46, 'Rhode Island', 'RI', 251, 0.00, NULL, 0, 0.00),
(47, 'South Carolina', 'SC', 251, 0.00, NULL, 0, 0.00),
(48, 'South Dakota', 'SD', 251, 0.00, NULL, 0, 0.00),
(49, 'Tennessee', 'TN', 251, 0.00, NULL, 0, 0.00),
(50, 'Texas', 'TX', 251, 0.00, NULL, 0, 0.00),
(52, 'Utah', 'UT', 251, 0.00, NULL, 0, 0.00),
(53, 'Virginia', 'VA', 251, 0.00, NULL, 0, 0.00),
(55, 'Vermont', 'VT', 251, 0.00, NULL, 0, 0.00),
(56, 'Washington', 'WA', 251, 0.00, NULL, 0, 0.00),
(57, 'Wisconsin', 'WI', 251, 0.00, NULL, 0, 0.00),
(58, 'West Virginia', 'WV', 251, 0.00, NULL, 0, 0.00),
(59, 'Wyoming', 'WY', 251, 0.00, NULL, 0, 0.00),
(65, 'Bedfordshire', 'BFD', 100, 15.00, NULL, 0, 0.00),
(66, 'Berkshire', 'BRK', 100, 15.00, NULL, 0, 0.00),
(67, 'Buckinghamshire', 'BUX', 100, 15.00, 'N', 0, 0.00),
(68, 'Cambridgeshire', 'CBE', 100, 15.00, 'N', 0, 0.00),
(69, 'Cheshire', 'CHS', 100, 15.00, 'N', 0, 0.00),
(70, 'Cornwall', 'CNL', 100, 15.00, 'N', 0, 0.00),
(71, 'Cumberland', 'CUL', 100, 15.00, 'N', 0, 0.00),
(72, 'Derbyshire', 'DYS', 100, 15.00, 'N', 0, 0.00),
(74, 'Dorset', 'DOR', 100, 15.00, 'N', 0, 0.00),
(75, 'Durham', 'DUR', 100, 15.00, 'N', 0, 0.00),
(76, 'Essex', 'ESX', 100, 15.00, 'N', 0, 0.00),
(77, 'Gloucestershire', 'GLS', 100, 15.00, 'N', 0, 0.00),
(78, 'Hampshire', 'HPH', 100, 15.00, 'N', 0, 0.00),
(79, 'Herefordshire', 'HEF', 100, 15.00, 'N', 0, 0.00),
(80, 'Hertfordshire', 'HFD', 100, 15.00, 'N', 0, 0.00),
(81, 'Huntingdonshire', 'HUN', 100, 15.00, 'N', 0, 0.00),
(82, 'Kent', 'KNT', 100, 15.00, 'N', 0, 0.00),
(83, 'Lancashire', 'LNH', 100, 15.00, 'N', 0, 0.00),
(84, 'Leicestershire', 'LEC', 100, 15.00, 'N', 0, 0.00),
(85, 'Lincolnshire', 'LCN', 100, 15.00, 'N', 0, 0.00),
(86, 'Middlesex', 'MDX', 100, 15.00, 'N', 0, 0.00),
(87, 'Norfolk', 'NOR', 100, 15.00, 'N', 0, 0.00),
(88, 'Northamptonshire', 'NHM', 100, 15.00, 'N', 0, 0.00),
(89, 'Northumberland', 'NLD', 100, 15.00, 'N', 0, 0.00),
(90, 'Nottinghamshire', 'NOT', 100, 15.00, 'N', 0, 0.00),
(91, 'Oxfordshire', 'OFE', 100, 15.00, 'N', 0, 0.00),
(92, 'Rutland', 'RUT', 100, 15.00, 'N', 0, 0.00),
(93, 'Shropshire', 'SPE', 100, 15.00, 'N', 0, 0.00),
(94, 'Somerset', 'SOM', 100, 15.00, 'N', 0, 0.00),
(95, 'Staffordshire', 'SFD', 100, 15.00, 'N', 0, 0.00),
(96, 'Suffolk', 'SFK', 100, 15.00, 'N', 0, 0.00),
(97, 'Surrey', 'SRY', 100, 15.00, 'N', 0, 0.00),
(98, 'Sussex', 'SSX', 100, 15.00, 'N', 0, 0.00),
(99, 'Warwickshire', 'WKS', 100, 15.00, 'N', 0, 0.00),
(100, 'Westmorland', 'WES', 18, 10.00, 'N', 0, 0.00),
(101, 'Wiltshire', 'WLT', 100, 15.00, 'N', 0, 0.00),
(102, 'Worcestershire', 'WOR', 100, 15.00, 'N', 0, 0.00),
(103, 'Yorkshire', 'YKS', 100, 15.00, 'N', 0, 0.00),
(196, 'Other', 'OTH', 100, 15.00, NULL, 0, 0.00),
(195, 'Merseyside', 'MSD', 100, 15.00, NULL, 0, 0.00),
(194, 'Value Added Tax', 'VAT', 100, 20.00, NULL, 0, 0.00),
(138, 'Aberdeenshire', 'ABD', 100, 15.00, 'N', 0, 0.00),
(139, 'Anglesey', 'AGY', 100, 15.00, 'N', 0, 0.00),
(140, 'Angus', 'ANS', 100, 15.00, 'N', 0, 0.00),
(141, 'Antrim', 'ANT', 100, 15.00, 'N', 0, 0.00),
(142, 'Argyllshire', 'ARL', 100, 15.00, 'N', 0, 0.00),
(143, 'Armagh', 'ARM', 100, 15.00, 'N', 0, 0.00),
(144, 'Ayrshire', 'AYR', 100, 15.00, 'N', 0, 0.00),
(145, 'Banffshire', 'BAN', 100, 15.00, 'N', 0, 0.00),
(146, 'Berwickshire', 'BEW', 100, 15.00, 'N', 0, 0.00),
(147, 'Brecknockshire', 'BRE', 100, 15.00, 'N', 0, 0.00),
(148, 'Buteshire', 'BUT', 100, 15.00, 'N', 0, 0.00),
(149, 'Caernarfonshire', 'CEA', 100, 15.00, 'N', 0, 0.00),
(150, 'Caithness', 'CAI', 100, 15.00, 'N', 0, 0.00),
(151, 'Cardiganshire', 'CGN', 100, 15.00, 'N', 0, 0.00),
(152, 'Carmarthenshire', 'CMN', 100, 15.00, 'N', 0, 0.00),
(153, 'Clackmannanshire', 'CLK', 100, 15.00, 'N', 0, 0.00),
(154, 'Cromartyshire', 'ROC', 100, 15.00, 'N', 0, 0.00),
(155, 'Denbighshire', 'DEN', 100, 15.00, 'N', 0, 0.00),
(156, 'Devon', 'DVN', 100, 15.00, 'N', 0, 0.00),
(157, 'Down', 'DOW', 100, 15.00, 'N', 0, 0.00),
(158, 'Dumfriesshire', 'DFS', 100, 15.00, 'N', 0, 0.00),
(159, 'Dunbartonshire', 'DNB', 100, 15.00, 'N', 0, 0.00),
(160, 'East Lothian', 'ELN', 100, 15.00, 'N', 0, 0.00),
(161, 'Fermanagh', 'FER', 100, 15.00, 'N', 0, 0.00),
(162, 'Fife', 'FIF', 100, 15.00, 'N', 0, 0.00),
(163, 'Flintshire', 'FLN', 100, 15.00, 'N', 0, 0.00),
(164, 'Glamorgan', 'GLA', 100, 15.00, 'N', 0, 0.00),
(165, 'Inverness-shire', 'INV', 100, 15.00, 'N', 0, 0.00),
(166, 'Kincardineshire', 'KCD', 100, 15.00, 'N', 0, 0.00),
(167, 'Kinross', 'KRS', 100, 15.00, 'N', 0, 0.00),
(168, 'Kirkcudbrightshire', 'KKD', 100, 15.00, 'N', 0, 0.00),
(169, 'Lanarkshire', 'LKS', 100, 15.00, 'N', 0, 0.00),
(170, 'Londonderry', 'LDY', 100, 15.00, 'N', 0, 0.00),
(171, 'Merioneth', 'MER', 100, 15.00, 'N', 0, 0.00),
(172, 'Midlothian', 'MLN', 100, 15.00, 'N', 0, 0.00),
(173, 'Monmouthshire', 'MON', 100, 15.00, 'N', 0, 0.00),
(174, 'Montgomeryshire', 'MGY', 100, 15.00, 'N', 0, 0.00),
(175, 'Morayshire', 'MOR', 100, 15.00, 'N', 0, 0.00),
(176, 'Nairnshire', 'NAI', 100, 15.00, 'N', 0, 0.00),
(177, 'Orkney', 'OKI', 100, 15.00, 'N', 0, 0.00),
(178, 'Peeblesshire', 'PEE', 100, 15.00, 'N', 0, 0.00),
(179, 'Pembrokeshire', 'PEM', 100, 15.00, 'N', 0, 0.00),
(180, 'Perthshire', 'PER', 100, 15.00, 'N', 0, 0.00),
(181, 'Radnorshire', 'RAD', 100, 15.00, 'N', 0, 0.00),
(182, 'Renfrewshire', 'RFW', 100, 15.00, 'N', 0, 0.00),
(183, 'Ross-shire', 'RO', 100, 15.00, 'N', 0, 0.00),
(184, 'Roxburghshire', 'ROX', 100, 15.00, 'N', 0, 0.00),
(185, 'Selkirkshire', 'SEL', 100, 15.00, 'N', 0, 0.00),
(186, 'Shetland', 'SHI', 100, 15.00, 'N', 0, 0.00),
(187, 'Stirlingshire', 'STI', 100, 15.00, 'N', 0, 0.00),
(188, 'Sutherland', 'SUT', 100, 15.00, 'N', 0, 0.00),
(189, 'Tyrone', 'TYR', 100, 15.00, 'N', 0, 0.00),
(190, 'West Lothian', 'WLN', 100, 15.00, 'N', 0, 0.00),
(191, 'Wigtownshire', 'WIG', 100, 15.00, 'N', 0, 0.00),
(192, 'Tyne and Wear', 'TW', 100, 15.00, 'N', 0, 0.00),
(197, 'Argyll', NULL, 100, 15.00, 'N', 0, 0.00),
(198, 'Avon', NULL, 100, 15.00, 'N', 0, 0.00),
(199, 'Cleveland', NULL, 100, 15.00, 'N', 0, 0.00),
(200, 'Clwyd', NULL, 100, 15.00, 'N', 0, 0.00),
(201, 'County Antrim', NULL, 100, 15.00, 'N', 0, 0.00),
(202, 'County rmagh', NULL, 100, 15.00, 'N', 0, 0.00),
(203, 'County Down', NULL, 100, 15.00, 'N', 0, 0.00),
(204, 'County Durham', NULL, 100, 15.00, 'N', 0, 0.00),
(205, 'County Fermanagh', NULL, 100, 15.00, 'N', 0, 0.00),
(206, 'County Londonderry', NULL, 100, 15.00, 'N', 0, 0.00),
(207, 'County Tyrone', NULL, 100, 15.00, 'N', 0, 0.00),
(208, 'Cumbria', NULL, 100, 15.00, 'N', 0, 0.00),
(209, 'Dyfed', NULL, 100, 15.00, 'N', 0, 0.00),
(210, 'East Sussex', NULL, 100, 15.00, 'N', 0, 0.00),
(211, 'Guernsey', NULL, 100, 15.00, 'N', 0, 0.00),
(212, 'Gwent', NULL, 100, 15.00, 'N', 0, 0.00),
(213, 'Gwynedd', NULL, 100, 15.00, 'N', 0, 0.00),
(214, 'Isle Of Arran', NULL, 100, 15.00, 'N', 0, 0.00),
(215, 'Isle Of Barra', NULL, 100, 15.00, 'N', 0, 0.00),
(216, 'Isle Of Benbecula', NULL, 100, 15.00, 'N', 0, 0.00),
(217, 'Isle Of Bute', NULL, 100, 15.00, 'N', 0, 0.00),
(218, 'Isle Of Canna', NULL, 100, 15.00, 'N', 0, 0.00),
(219, 'Isle Of Coll', NULL, 100, 15.00, 'N', 0, 0.00),
(220, 'Isle Of olonsay', NULL, 100, 15.00, 'N', 0, 0.00),
(221, 'Isle Of Cumbrae', NULL, 100, 15.00, 'N', 0, 0.00),
(222, 'Isle Of Eigg', NULL, 100, 15.00, 'N', 0, 0.00),
(223, 'Isle Of Gigha', NULL, 100, 15.00, 'N', 0, 0.00),
(224, 'Isle Of Harris', NULL, 100, 15.00, 'N', 0, 0.00),
(225, 'Isle Of Iona', NULL, 100, 15.00, 'N', 0, 0.00),
(226, 'Isle Of Islay', NULL, 100, 15.00, 'N', 0, 0.00),
(227, 'Isle Of Jura', NULL, 100, 15.00, 'N', 0, 0.00),
(228, 'Isle Of Lewis', NULL, 100, 15.00, 'N', 0, 0.00),
(229, 'Isle Of Man', NULL, 100, 15.00, 'N', 0, 0.00),
(230, 'Isle Of Mull', NULL, 100, 15.00, 'N', 0, 0.00),
(231, 'Isle Of North Uist', NULL, 100, 15.00, 'N', 0, 0.00),
(232, 'Isle Of Rum', NULL, 100, 15.00, 'N', 0, 0.00),
(233, 'Isle Of Scalpay', NULL, 100, 15.00, 'N', 0, 0.00),
(234, 'Isle Of Skye', NULL, 100, 15.00, 'N', 0, 0.00),
(235, 'Isle Of South ist', NULL, 100, 15.00, 'N', 0, 0.00),
(236, 'Isle Of Tiree', NULL, 100, 15.00, 'N', 0, 0.00),
(237, 'Isle Of Wight', NULL, 100, 15.00, 'N', 0, 0.00),
(238, 'Isles Of Scilly', NULL, 100, 15.00, 'N', 0, 0.00),
(239, 'Jersey', NULL, 100, 15.00, 'N', 0, 0.00),
(240, 'Kinross-Shire', NULL, 100, 15.00, 'N', 0, 0.00),
(241, 'London', NULL, 100, 15.00, 'N', 0, 0.00),
(242, 'Mid Glamorgan', NULL, 100, 15.00, 'N', 0, 0.00),
(243, 'North Humberside', NULL, 100, 15.00, 'N', 0, 0.00),
(244, 'North Yorkshire', NULL, 100, 15.00, 'N', 0, 0.00),
(245, 'Powys', NULL, 100, 15.00, 'N', 0, 0.00),
(246, 'Shetland Islands', NULL, 100, 15.00, 'N', 0, 0.00),
(247, 'South lamorgan', NULL, 100, 15.00, 'N', 0, 0.00),
(248, 'South Humberside', NULL, 100, 15.00, 'N', 0, 0.00),
(249, 'South Yorkshire', NULL, 100, 15.00, 'N', 0, 0.00),
(250, 'West Glamorgan', NULL, 100, 15.00, 'N', 0, 0.00),
(251, 'West Midlands', NULL, 100, 15.00, 'N', 0, 0.00),
(252, 'West Sussex', NULL, 100, 15.00, 'N', 0, 0.00),
(253, 'West Yorkshire', NULL, 100, 15.00, 'N', 0, 0.00);

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_contactus` (
  `iContactId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vName` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vTitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vOrganisation` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAddress1` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAddress2` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCity` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCounty` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vZipcode` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCountry` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vWorkPhone` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vFax` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vEmail` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vComments` text COLLATE utf8_unicode_ci NOT NULL,
  `tmAddDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iContactId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_CustomerRatings` (
  `iCustRateid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iProductid_FK` int(11) NOT NULL DEFAULT '0',
  `iExcellent` int(11) NOT NULL DEFAULT '0',
  `iGreat` int(11) NOT NULL DEFAULT '0',
  `iGood` int(11) NOT NULL DEFAULT '0',
  `iFair` int(11) NOT NULL DEFAULT '0',
  `iPoor` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iCustRateid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_CustomerReviews` (
  `iCustRevid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iItemid_FK` int(11) NOT NULL DEFAULT '0',
  `iCustomerid_FK` int(11) NOT NULL DEFAULT '0',
  `vTitle` varchar(150) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `vComment` text COLLATE utf8_unicode_ci NOT NULL,
  `vRank` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iDisplay` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `tmDateAdd` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iState` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`iCustRevid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_CustomerReviewsHelpful` (
  `iHelpid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iCustId_FK` int(11) NOT NULL DEFAULT '0',
  `iReviewId_FK` int(11) NOT NULL DEFAULT '0',
  `iStatus` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iHelpid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_Customers` (
  `iCustmerid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vFirstName` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vLastName` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vEmail` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vPassword` text COLLATE utf8_unicode_ci NOT NULL,
  `vAddress1` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vAddress2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCity` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vState` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vStateName` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vCountry` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vZip` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCompany` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPhone` varchar(15) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vHomePage` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iMailList` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `vRetail` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `fMemberPoints` float(10,0) NOT NULL DEFAULT '0',
  `tmSignupDate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iCustomerCount` int(11) NOT NULL DEFAULT '0',
  `vAccountreference` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `iNoOfDownloads` int(11) NOT NULL DEFAULT '3',
  `iStatus` int(11) NOT NULL DEFAULT '1',
  `iRegistered` int(11) NOT NULL DEFAULT '1',
  `vRecovery` text COLLATE utf8_unicode_ci,
  `tRequestTime` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`iCustmerid_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbUser_vendors` (
  `iVendorid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vCompany` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAddress1` varchar(75) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vAddress2` varchar(75) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCity` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vState` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vStateName` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vZip` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vCountry` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPhone` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPhone2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vContact` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vEmail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vWebsite` varchar(75) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vComments` text COLLATE utf8_unicode_ci,
  `vImage` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmBuildDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `tmEditDate` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iAdminUser` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `iStatus` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iVendorid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tbWish_emails` (
  `iWishid_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iCustomerid_FK` int(11) DEFAULT NULL,
  `vEmail` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iWishid_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}tb_frooglesettings` (
  `fid_Pk` int(11) NOT NULL AUTO_INCREMENT,
  `vServer` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `vUsername` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `vPassword` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`fid_Pk`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

INSERT INTO `{{prefix}}tb_frooglesettings` (`fid_Pk`, `vServer`, `vUsername`, `vPassword`) VALUES
(1, '', '', '');

CREATE TABLE IF NOT EXISTS `{{prefix}}temp_cart` (
  `iTmpCartId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `vSessionId` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iProdId_FK` int(11) NOT NULL DEFAULT '0',
  `iQty` int(11) NOT NULL DEFAULT '0',
  `iGiftWrap` int(11) NOT NULL DEFAULT '0',
  `fVolDiscount` float(10,2) NOT NULL DEFAULT '0.00',
  `iBackOrder` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iTmpCartId_PK`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}temp_choices` (
  `iTmpChoiceId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iTmpCartId_FK` int(11) NOT NULL DEFAULT '0',
  `iProdId_Fk` int(11) NOT NULL DEFAULT '0',
  `iTmpChoiceId_FK` int(11) NOT NULL DEFAULT '0',
  `vChoiceVal` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `iQty` tinyint(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`iTmpChoiceId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}temp_images` (
  `iImagesPK` int(11) NOT NULL AUTO_INCREMENT,
  `vImages` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `tmTimeInserted` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`iImagesPK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `{{prefix}}temp_options` (
  `iTempOptId_PK` int(11) NOT NULL AUTO_INCREMENT,
  `iTmpCartId_FK` int(11) NOT NULL DEFAULT '0',
  `iProdId_Fk` int(11) NOT NULL DEFAULT '0',
  `iOptId_FK` int(11) NOT NULL DEFAULT '0',
  `vOptVal` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`iTempOptId_PK`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;